#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Build and sign the Tracks Music watch app.
#
#   ./build.sh                    # device-agnostic: compiles, type-checks, signs
#   ./build.sh all                # every music-capable watch: what a release ships
#   ./build.sh fenix6xpro         # one watch: quicker, for trying a change on yours
#   ./build.sh fenix6xpro --dev   # simulator build with a baked-in music server
#
# A device-targeted build needs that device's definition in
# ~/.Garmin/ConnectIQ/Devices/, which the Connect IQ SDK Manager downloads
# after a (free) Garmin account login. For `all`, download every device: the
# list of watches is read from those definitions (see devices.py), so a device
# not downloaded is a device not built for.
#
# --dev exists because the simulator has no phone to pair with. It reads
#
#   TRACKS_DEV_URL   TRACKS_DEV_USER   TRACKS_DEV_PASS
#   [TRACKS_DEV_PLAYLISTS]   [TRACKS_DEV_PLAY]   [TRACKS_DEV_PROBE]
#   [TRACKS_DEV_CONFIG_URL]
#
# from the environment (or from ./.dev.env, which is gitignored) and compiles
# them in via a generated source file that only a --dev build ever includes. A
# dev build is never bundled into the phone app.
set -euo pipefail

SDK_ROOT="${CIQ_SDK:-$HOME/.Garmin/ConnectIQ/Sdks/connectiq-sdk-9.2.0}"
KEY="${CIQ_KEY:-$HOME/.Garmin/ConnectIQ/developer_key.der}"
DEVICE=""
DEV=0
for arg in "$@"; do
    case "$arg" in
        --dev) DEV=1 ;;
        *) DEVICE="$arg" ;;
    esac
done
OUT="${OUT:-build/TracksMusic.prg}"

[ -x "$SDK_ROOT/bin/monkeyc" ] || { echo "No SDK at $SDK_ROOT — set CIQ_SDK." >&2; exit 1; }
[ -f "$KEY" ] || {
    echo "No developer key at $KEY. Generate one with:" >&2
    echo "  openssl genrsa -out developer_key.pem 4096" >&2
    echo "  openssl pkcs8 -topk8 -inform PEM -outform DER \\" >&2
    echo "          -in developer_key.pem -out developer_key.der -nocrypt" >&2
    exit 1
}

cd "$(dirname "$0")"

# A shippable build compiles from a fixed, neutral directory. The .prg is not
# stripped (see below), and an unstripped .prg records the absolute path of
# every source file it was built from — so a build run in place would put the
# builder's home directory inside every watch app the phone bundles. Staging
# under one fixed path also makes the paths identical whoever builds it.
# --dev builds stay where they are: they are never bundled, and their probe
# file may be given as a path relative to here.
STAGE=/tmp/tracks-watchapp
if [ "$DEV" = 0 ] && [ "$PWD" != "$STAGE" ]; then
    rm -rf "$STAGE"
    mkdir -p "$STAGE"
    cp -r manifest.xml monkey.jungle source resources devices.py build.sh "$STAGE"/
    TRACKS_ASSETS="$(cd .. && pwd)/mobile/app/src/main/assets/watchapp" "$STAGE/build.sh" "$@"
    rm -rf build
    cp -r "$STAGE/build" build      # outputs land where they always have
    exit 0
fi

mkdir -p "$(dirname "$OUT")"

JUNGLE=monkey.jungle
if [ "$DEV" = 1 ]; then
    [ -f .dev.env ] && . ./.dev.env
    : "${TRACKS_DEV_URL:?set TRACKS_DEV_URL (or put it in .dev.env)}"
    : "${TRACKS_DEV_USER:?set TRACKS_DEV_USER}"
    : "${TRACKS_DEV_PASS:?set TRACKS_DEV_PASS}"
    mkdir -p build/dev
    if [ -n "${TRACKS_DEV_PLAY+set}" ]; then PLAY="\"$TRACKS_DEV_PLAY\""; else PLAY=null; fi
    # TRACKS_DEV_CONFIG_URL stands in for the phone: the app asks it instead
    # of tracks.invalid, so revisions and log out can be driven from a local
    # file in the simulator (which has no phone).
    if [ -n "${TRACKS_DEV_CONFIG_URL:-}" ]; then CONFIG_URL="\"$TRACKS_DEV_CONFIG_URL\""; else CONFIG_URL=null; fi
    # Comma-separated playlist ids to start with; the two built-ins by default.
    PLAYLISTS=$(printf '%s' "${TRACKS_DEV_PLAYLISTS:-~starred,~recent}" | sed 's/[^,][^,]*/"&"/g')
    cat > build/dev/DevConfig.mc <<MC
// Generated by build.sh --dev. Not committed; not in any non-dev build.
module TracksConfig {
    (:devconfig)
    function devConfig() {
        return {
            "url" => "${TRACKS_DEV_URL%/}",
            "user" => "$TRACKS_DEV_USER",
            "password" => "$TRACKS_DEV_PASS"
        };
    }

    (:devconfig)
    function devPlaylists() {
        return [$PLAYLISTS];
    }

    (:devconfig)
    function devConfigUrl() {
        return $CONFIG_URL;
    }

    // Changes every build, so each new build syncs exactly once on launch.
    (:devconfig)
    function devGeneration() {
        return "$(date +%s)";
    }

    // TRACKS_DEV_PLAY=<playlist id> plays that instead of syncing; "" plays all.
    (:devconfig)
    function devPlay() {
        return $PLAY;
    }
}
MC
    # TRACKS_DEV_PROBE: a Monkey C file to compile in as the dev probe. It must
    # define `TracksConfig.devProbe()` under (:devconfig); the app calls it on
    # start and does nothing else when it returns true.
    rm -f build/dev/Probe.mc
    if [ -n "${TRACKS_DEV_PROBE:-}" ]; then
        cp "$TRACKS_DEV_PROBE" build/dev/Probe.mc
        echo "Dev probe: $TRACKS_DEV_PROBE"
    else
        cat > build/dev/Probe.mc <<MC
module TracksConfig {
    (:devconfig)
    function devProbe() {
        return false;
    }
}
MC
    fi
    cat > build/dev/dev.jungle <<JUNGLE
project.manifest = ../../manifest.xml
base.sourcePath = ../../source;.
base.resourcePath = ../../resources
base.excludeAnnotations = nodev
JUNGLE
    JUNGLE=build/dev/dev.jungle
    OUT="${OUT%.prg}-dev.prg"
    echo "Dev build: music server $TRACKS_DEV_URL as $TRACKS_DEV_USER"
fi

args=(-f "$JUNGLE" -o "$OUT" -y "$KEY" -w)

# Not stripped, and that is a decision rather than an oversight.
#
# -r drops the .prg from 143 KB to 33 KB, which over a 23-byte-MTU Bluetooth
# link is most of the install time — so it was tried. The watch installed the
# result and then did not list Tracks Music under Music Providers at all,
# which is a far worse outcome than a slow install. The app's own resources do
# survive -r (its strings are all still in the binary), so the cause is
# something else and is not yet understood.
#
# Leaving it off until that is explained and tested on hardware. Anyone
# revisiting this: -O z makes the file *bigger*, and -O 3 buys nothing on top
# of -r, so stripping is the only lever here worth the risk.

ASSETS="${TRACKS_ASSETS:-../mobile/app/src/main/assets/watchapp}"

# Every watch at once, into build/all/<id>/, then one bundle for the phone.
#
# A directory per device is not tidiness: monkeyc writes its intermediate gen/
# and mir/ trees beside the output file, and parallel builds sharing one
# directory corrupt each other — a third of them failed with "A critical error
# has occurred" or undefined symbols until each had its own.
if [ "$DEVICE" = all ]; then
    [ "$DEV" = 1 ] && { echo "--dev is for one device in the simulator, not all." >&2; exit 1; }
    ./devices.py manifest --check
    rm -rf build/all
    jobs="${JOBS:-$(nproc)}"
    count=$(./devices.py list | wc -l)
    echo "Building $count devices, $jobs at a time..."
    failed=$(./devices.py list | xargs -P "$jobs" -I{} sh -c '
        mkdir -p build/all/{}
        "$0" "$@" -d {} -o build/all/{}/{}.prg > build/all/{}.log 2>&1 || echo {}
    ' "$SDK_ROOT/bin/monkeyc" -f "$JUNGLE" -y "$KEY" -w | tr '\n' ' ')
    if [ -n "$failed" ]; then
        echo "Failed: $failed(logs in build/all/<id>.log)" >&2
        exit 1
    fi
    rm -rf "$ASSETS"
    ./devices.py bundle build/all "$ASSETS"
    exit 0
fi

if [ -n "$DEVICE" ]; then
    if [ ! -d "$HOME/.Garmin/ConnectIQ/Devices/$DEVICE" ]; then
        echo "No definition for '$DEVICE' in ~/.Garmin/ConnectIQ/Devices/." >&2
        echo "Open the Connect IQ SDK Manager, sign in, and download it." >&2
        exit 1
    fi
    args+=(-d "$DEVICE")
else
    # No device: compile against the SDK's own API database. This still parses,
    # type-checks and signs — it just is not targeted at a watch. Useful in CI,
    # where downloading device definitions needs an account.
    args+=(-a "$SDK_ROOT/bin/api.db"
           -b "$SDK_ROOT/bin/api.mir"
           -i "$SDK_ROOT/bin/api.debug.xml")
fi

"$SDK_ROOT/bin/monkeyc" "${args[@]}"
echo "Built ${DEVICE:+for $DEVICE }-> $OUT ($(stat -c%s "$OUT") bytes)"

# Bundle into the Android app, which is what actually pushes it to the watch.
#
# Only for a device-targeted build. A device-agnostic .prg compiles, type-checks
# and signs, but it is not built against any watch's screen or memory profile —
# shipping one would produce an install failure that looks like a bug in the
# phone app rather than a build that was never meant for a watch.
#
# A one-device build replaces the whole bundle with a bundle of one, in the
# same format, so the phone reads it the same way. Run `./build.sh all` before
# a release: the phone refuses a watch it has no build for, by name.
if [ "$DEV" = 1 ]; then
    echo "Not bundled: dev build carries a baked-in server. Run it in the simulator:"
    echo "  $SDK_ROOT/bin/monkeydo $OUT $DEVICE"
elif [ -n "$DEVICE" ]; then
    rm -rf build/one "$ASSETS"
    mkdir -p "build/one/$DEVICE"
    cp "$OUT" "build/one/$DEVICE/$DEVICE.prg"
    ./devices.py bundle build/one "$ASSETS"
    echo "Only $DEVICE is bundled. ./build.sh all bundles every watch."
else
    echo "Not bundled: device-agnostic build. Re-run with a device id, or all, to ship it."
fi
