# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
SQLAlchemy models for the strength training feature.

ExerciseLibrary  — curated exercise definitions with Garmin FIT mapping,
                   muscle groups, equipment requirements, and sport relevance.
UserExerciseStrength — per-user progressive overload state for each exercise
                       (e1RM, last weight, progression stage, session count).
"""

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey, Integer,
    String, Text, Index, UniqueConstraint,
)
from sqlalchemy.sql import func

from app.database import Base, PJson
from app.models.sync import Synced, sync_indexes


class ExerciseLibrary(Base):
    """
    Master exercise reference table.

    Populated by migration 029 and not user-editable.  The garmin_category and
    garmin_subtype fields map directly to exercise_names.py so that strength
    FIT files generated by the planner will display animations on supported
    Garmin watches (Forerunner 955/965, Fenix 7+, Epix).
    """
    __tablename__ = "exercise_library"

    id                = Column(Integer, primary_key=True)
    name              = Column(String(128), nullable=False, unique=True)

    # Garmin FIT SDK category and subtype — matches exercise_names.py _NAMES table.
    # NULL for mobility/stretch exercises that have no Garmin equivalent.
    garmin_category   = Column(String(64))
    garmin_subtype    = Column(Integer)

    # True when (garmin_category, garmin_subtype) is in Garmin Connect's
    # public animation manifest (Exercises.json / Yoga.json / etc.) — i.e.
    # the watch is expected to play an animation for this exercise during a
    # workout. For library rows it comes from spec/library (loaded by
    # app.seed); custom exercises set it on save.
    has_animation     = Column(Boolean, nullable=False, default=False,
                               server_default="false")

    # Muscle group arrays stored as PJson for schema flexibility.
    # Values: quads, hamstrings, glutes, calves, hip_flexors, lower_back,
    #         upper_back, lats, chest, shoulders, biceps, triceps, core,
    #         forearms, obliques, hip_abductors
    primary_muscles   = Column(PJson, nullable=False, default=lambda: [])
    secondary_muscles = Column(PJson, nullable=False, default=lambda: [])

    # Equipment required: bodyweight, dumbbell, barbell, cable, machine,
    #                     kettlebell, band
    equipment         = Column(PJson, nullable=False, default=lambda: ["bodyweight"])

    # Movement pattern for injury-based filtering:
    # squat, hinge, push, pull, carry, rotation, isometric, plyometric, isolation
    movement_pattern  = Column(String(32))

    # Sport relevance scores 0–3 per sport family.
    # {"running": 3, "cycling": 2, "climbing": 1, "paddling": 3, ...}
    sport_relevance   = Column(PJson, nullable=False, default=lambda: {})

    # 1=beginner, 2=intermediate (technique required), 3=advanced (high skill)
    difficulty        = Column(Integer, nullable=False, default=1)

    # Multi-joint compound movements are prioritised over isolation exercises
    is_compound       = Column(Boolean, nullable=False, default=True)

    # Optional coaching note displayed in the workout card UI
    description       = Column(Text)

    # Step-by-step how-to instructions (newline-separated steps)
    instructions      = Column(Text)

    # Short coaching cues (2-3 imperative form reminders, e.g. "Brace your core",
    # "Drive through mid-foot"). Surfaced in step rows, the session runner, and
    # the exercise detail modal. Library cues come from spec/library.
    cues              = Column(PJson, nullable=False, default=lambda: [],
                               server_default="[]")

    created_at        = Column(DateTime(timezone=True), server_default=func.now())


class UserExercisePreference(Base, Synced):
    """
    Per-user preference for a named exercise (library or custom).

    preference='preferred' → algorithm prioritises it when building sessions.
    preference='excluded'  → algorithm never schedules it.
    No row = neutral (available but not prioritised).
    """
    __tablename__ = "user_exercise_preferences"

    id            = Column(Integer, primary_key=True)
    user_id       = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                           nullable=False)
    exercise_name = Column(String(128), nullable=False)
    preference    = Column(String(16), nullable=False, default="preferred")

    __table_args__ = (UniqueConstraint("user_id", "exercise_name"),)


sync_indexes(UserExercisePreference)


class UserCustomExercise(Base, Synced):
    """
    User-created exercise that supplements the curated library.

    Shares the same schema as ExerciseLibrary so it can be dropped into the
    exercise pool at plan generation time without special handling.
    """
    __tablename__ = "user_custom_exercises"

    id                = Column(Integer, primary_key=True)
    user_id           = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                               nullable=False)
    name              = Column(String(128), nullable=False)
    primary_muscles   = Column(PJson, nullable=False, default=lambda: [])
    secondary_muscles = Column(PJson, nullable=False, default=lambda: [])
    equipment         = Column(PJson, nullable=False, default=lambda: ["bodyweight"])
    movement_pattern  = Column(String(32))
    is_compound       = Column(Boolean, nullable=False, default=True)
    difficulty        = Column(Integer, nullable=False, default=1)
    description       = Column(Text)
    instructions      = Column(Text)
    cues              = Column(PJson, nullable=False, default=lambda: [],
                               server_default="[]")
    # Slug of a bundled movement animation the user picked for this custom
    # exercise (frontend animations/poses/*.json). NULL = no animation.
    viewer_slug       = Column(String(64))
    default_sets      = Column(Integer, nullable=False, default=3)
    default_reps      = Column(Integer, nullable=False, default=10)
    garmin_category   = Column(String(64))
    garmin_subtype    = Column(Integer)
    has_animation     = Column(Boolean, nullable=False, default=False,
                               server_default="false")
    created_at        = Column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (UniqueConstraint("user_id", "name"),)


sync_indexes(UserCustomExercise)


class AnimationConfirmation(Base, Synced):
    """
    Per-(device-model, exercise) confirmation that an animation plays — or
    explicitly does NOT play — on a specific Garmin watch model.

    Identity: keyed by (product_id, garmin_category, garmin_subtype, user_id).
    product_id is Garmin's device ID (e.g. 3291 for Fenix 6X Pro Solar) —
    confirmations are shared across users within an instance when they own
    the same model, so a family of 3 owning the same Fenix-6X collectively
    populates the dataset.

    The four-state animation tag rendered to the UI is derived from this
    table plus the bundled garmin_animations manifest:
      - confirmed_yes  → at least one user with this product_id marked it
                          animates and no one has marked it doesn't (or the
                          requesting user themself marked it animates).
      - confirmed_no   → at least one user with this product_id marked it
                          doesn't animate (and the requesting user hasn't
                          overridden with a yes).
      - likely         → no confirmation exists; (cat, subtype) is in the
                          manifest so it's likely-but-unverified.
      - unknown        → not in the manifest at all (no Garmin animation
                          asset).

    Removing a confirmation row reverts that user's contribution; the
    aggregate verdict for the device falls back to the remaining users.
    """
    __tablename__ = "animation_confirmations"

    id              = Column(Integer, primary_key=True)
    product_id      = Column(Integer, nullable=False)        # Garmin device id
    garmin_category = Column(String(64), nullable=False)
    garmin_subtype  = Column(Integer, nullable=False)
    animates        = Column(Boolean, nullable=False)
    user_id         = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                              nullable=False)
    confirmed_at    = Column(DateTime(timezone=True), server_default=func.now(),
                              onupdate=func.now())

    __table_args__ = (
        UniqueConstraint("product_id", "garmin_category", "garmin_subtype",
                          "user_id", name="uq_animation_confirmation_per_user"),
        Index("ix_animation_confirmations_lookup",
               "product_id", "garmin_category", "garmin_subtype"),
    )


sync_indexes(AnimationConfirmation)


class UserExerciseStrength(Base, Synced):
    """
    Per-user, per-exercise progressive overload tracking state.

    Updated automatically whenever a strength FIT file is imported (via
    match_activity_to_workout → _update_strength_fingerprint).  Also updated
    on manual log entries.  Used at plan generation time to prescribe
    appropriate weights via e1RM → training percentage.

    1RM formula: average of Epley + Brzycki + Wathan (most accurate for 2–10 reps).
    Accuracy: ±5% for 2–10 reps; avoid estimating from >10 reps.

    Progression stages driven by sessions_completed (matches NOTES.md section 5):
      linear            (0–19)  — add 2.5–5 kg when all reps completed at RPE ≤ 7
      weekly_undulating (20–99) — rotate hypertrophy/strength/power week pattern
      dup               (100+)  — daily undulating: vary rep range each session
    """
    __tablename__ = "user_exercise_strength"

    id                     = Column(Integer, primary_key=True)
    user_id                = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"),
                                    nullable=False)
    exercise_name          = Column(String(128), nullable=False)

    # Averaged 1RM estimate — primary progressive overload metric
    estimated_1rm_kg       = Column(Float)
    # A 1RM the user set by hand. Kept apart from the estimate because the
    # estimate is derived — every device recomputes it from sessions — while
    # this is something a person said, and is the only part of the row that
    # syncs (`one_rep_max` in spec/sync.yaml).
    override_1rm_kg        = Column(Float)

    # Most recent logged set — seed for next session prescription
    last_weight_kg         = Column(Float)
    last_reps              = Column(Integer)

    # Total volume load from the most recent session (sets × reps × weight_kg).
    # Tracked as hypertrophy stimulus — needs to increase over time.
    last_session_volume_kg = Column(Float)

    sessions_completed     = Column(Integer, nullable=False, default=0)
    progression_stage      = Column(String(32), nullable=False, default="linear")

    last_updated           = Column(DateTime(timezone=True),
                                    server_default=func.now(), onupdate=func.now())

    __table_args__ = (UniqueConstraint("user_id", "exercise_name"),
                       Index("ix_user_ex_strength_user", "user_id"))


sync_indexes(UserExerciseStrength)
