# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Static FIT exercise lookup tables (data only — no logic lives here).

Two tables, both keyed off the Garmin FIT ``exercise_category`` profile:

* ``_NAMES``      — (category_str, subtype_int) -> human-readable exercise name.
* ``_CATEGORY_ID`` — exercise_category enum int -> canonical snake_case name.

``category_str`` matches fitdecode's exercise_category enum values (lowercase
snake_case). ``subtype_int`` is the raw uint16 from the FIT set message field 8.

Source: Garmin FIT Java SDK (Profile Version 21.205.0), plus the firmware
category extensions noted inline below.

Consumed by :mod:`app.parsers.exercise_names.resolver`; not part of the public
package interface.
"""

_NAMES: dict[tuple[str, int], str] = {
    # ── BENCH_PRESS (0) ───────────────────────────────────────────────────
    ("bench_press",  1): "Barbell Bench Press",
    ("bench_press",  3): "Barbell Floor Press",
    ("bench_press",  4): "Close Grip Barbell Bench Press",
    ("bench_press",  5): "Decline Dumbbell Bench Press",
    ("bench_press",  6): "Dumbbell Bench Press",
    ("bench_press",  7): "Dumbbell Floor Press",
    ("bench_press",  8): "Incline Barbell Bench Press",
    ("bench_press",  9): "Incline Dumbbell Bench Press",
    ("bench_press", 13): "Neutral Grip Dumbbell Bench Press",
    ("bench_press", 18): "Reverse Grip Barbell Bench Press",
    ("bench_press", 21): "Single Arm Dumbbell Bench Press",
    ("bench_press", 25): "Wide Grip Barbell Bench Press",
    ("bench_press", 26): "Alternating Dumbbell Chest Press",
    ("bench_press", 27): "Band Bench Press",
    ("bench_press", 28): "Board Press",
    ("bench_press", 29): "Cable Chest Press",
    ("bench_press", 30): "Chest Press",
    ("bench_press", 31): "Close Grip Medicine Ball Push Up",

    # ── CALF_RAISE (1) ────────────────────────────────────────────────────
    ("calf_raise",  0): "3-Way Calf Raise",
    ("calf_raise",  6): "Barbell Calf Raise",
    ("calf_raise", 10): "Donkey Calf Raise",
    ("calf_raise", 11): "Double Leg Calf Raise",
    ("calf_raise", 14): "Leg Press Calf Raise",
    ("calf_raise", 15): "Seated Calf Raise",
    ("calf_raise", 16): "Single Leg Calf Raise",
    ("calf_raise", 17): "Standing Calf Raise",

    # ── CORE (5) ──────────────────────────────────────────────────────────
    ("core",  0): "Ab Wheel",
    ("core",  3): "Barbell Rollout",
    ("core",  4): "Body Bar Oblique Twist",
    ("core",  5): "Cable Core Press",
    ("core",  6): "Cable Side Bend",
    ("core",  7): "Dead Bug",
    ("core",  8): "Elbow to Knee",
    ("core",  9): "Eyebrow Raise",
    ("core", 10): "Floor Hip Circles",
    ("core", 11): "Floor Hyperextension",
    ("core", 12): "Floor Reach",
    ("core", 13): "Flutter Kicks",
    ("core", 14): "Foam Roll Ab Crunch",
    ("core", 15): "Front Lever",
    ("core", 16): "Hip Press",
    ("core", 17): "Hollow Hold",
    ("core", 18): "Inchworm",
    ("core", 19): "Kneeling Plank",
    ("core", 20): "Kneeling Wheel Rollout",
    ("core", 21): "Modified Front Lever",
    ("core", 22): "Open Knee Tucks",
    ("core", 23): "Overhead Walk",
    ("core", 24): "Renegade Row",
    ("core", 25): "Reverse Curl",
    ("core", 26): "Single Leg Lateral Plank Walk",
    ("core", 27): "Spider Plank",
    ("core", 28): "Straight Arm Plank Shoulder Touch",
    ("core", 29): "Swiss Ball Ab Rollout",
    ("core", 30): "Swiss Ball Oblique Crunch",
    ("core", 31): "Towel Pull",

    # ── CRUNCH (6) ────────────────────────────────────────────────────────
    ("crunch",  0): "Bicycle Crunch",
    ("crunch",  1): "Cable Crunch",
    ("crunch",  2): "Circular Arm Crunch",
    ("crunch",  3): "Crossed Arms Crunch",
    ("crunch",  4): "Double Crunch",
    ("crunch",  5): "Full Crunch",
    ("crunch",  6): "Heel Touch",
    ("crunch",  7): "Medicine Ball Sit Up",
    ("crunch",  8): "Oblique Crunch",
    ("crunch",  9): "One Arm Crunch",
    ("crunch", 10): "Plate Crunch",
    ("crunch", 11): "Reverse Crunch",
    ("crunch", 12): "Seated Barbell Twist",
    ("crunch", 13): "Side to Side Crunch and Weave",
    ("crunch", 14): "Toe Touch",
    ("crunch", 15): "Twisting Crunch",
    ("crunch", 16): "Weighted Bicycle Crunch",
    ("crunch", 17): "Weighted Cable Crunch",
    ("crunch", 18): "Weighted Crunch",
    ("crunch", 19): "Weighted Double Crunch",
    ("crunch", 20): "Weighted Oblique Crunch",
    ("crunch", 21): "Weighted Reverse Crunch",

    # ── CURL (7) ──────────────────────────────────────────────────────────
    ("curl",  0): "Alternating Dumbbell Biceps Curl",
    ("curl",  3): "Barbell Biceps Curl",
    ("curl",  4): "Barbell Reverse Wrist Curl",
    ("curl",  5): "Barbell Wrist Curl",
    ("curl",  6): "Behind the Back Barbell Curl",
    ("curl",  7): "Behind the Back One Arm Cable Curl",
    ("curl",  8): "Cable Biceps Curl",
    ("curl",  9): "Cable Hammer Curl",
    ("curl", 10): "Cheating Barbell Biceps Curl",
    ("curl", 11): "Close Grip Ez Bar Biceps Curl",
    ("curl", 12): "Cross Body Dumbbell Hammer Curl",
    ("curl", 13): "Dead Hang Biceps Curl",
    ("curl", 14): "Decline Hammer Curl",
    ("curl", 15): "Dumbbell Biceps Curl",
    ("curl", 16): "Dumbbell Hammer Curl",
    ("curl", 17): "Dumbbell Reverse Wrist Curl",
    ("curl", 18): "Dumbbell Wrist Curl",
    ("curl", 19): "Ez Bar Preacher Curl",
    ("curl", 20): "Forward Bend Biceps Curl",
    ("curl", 21): "Hammer Curl to Press",
    ("curl", 22): "Incline Dumbbell Biceps Curl",
    ("curl", 23): "Incline Offset Thumb Dumbbell Curl",
    ("curl", 24): "Kettlebell Biceps Curl",
    ("curl", 25): "Lying Concentration Cable Curl",
    ("curl", 26): "One Arm Preacher Curl",
    ("curl", 27): "Plate Pinch Curl",
    ("curl", 28): "Preacher Curl",
    ("curl", 29): "Reverse Barbell Biceps Curl",
    ("curl", 30): "Reverse Cable Hammer Curl",
    ("curl", 31): "Seated Alternating Dumbbell Biceps Curl",
    ("curl", 32): "Seated Dumbbell Biceps Curl",
    ("curl", 33): "Seated Ez Bar Biceps Curl",
    ("curl", 34): "Seated One Arm Dumbbell Preacher Curl",
    ("curl", 35): "Single Arm Biceps Curl",
    ("curl", 36): "Slow Concentration Curl",
    ("curl", 37): "Standing Dumbbell Biceps Curl",
    ("curl", 38): "Standing Ez Bar Biceps Curl",
    ("curl", 39): "Standing One Arm Cable Curl",
    ("curl", 40): "Step Up with Dumbbell Curl",
    ("curl", 41): "Wide Grip Ez Bar Biceps Curl",
    ("curl", 42): "Zottman Curl",
    ("curl", 43): "3 Way Biceps Curl",
    ("curl", 44): "Barbell 21s",
    ("curl", 45): "Kneeling Cable Concentration Curl",
    ("curl", 46): "Dumbbell Biceps Curl",

    # ── DEADLIFT (8) ──────────────────────────────────────────────────────
    ("deadlift",  0): "Barbell Deadlift",
    ("deadlift",  1): "Barbell Straight Leg Deadlift",
    ("deadlift",  2): "Dumbbell Deadlift",
    ("deadlift",  3): "Dumbbell Single Leg Deadlift",
    ("deadlift",  4): "Dumbbell Straight Leg Deadlift",
    ("deadlift",  5): "Kettlebell Floor Deadlift",
    ("deadlift",  6): "One Arm One Leg Deadlift",
    ("deadlift",  7): "Rack Pull",
    ("deadlift",  8): "Rotational Dumbbell Straight Leg Deadlift",
    ("deadlift",  9): "Single Arm Deadlift",
    ("deadlift", 10): "Single Leg Barbell Deadlift",
    ("deadlift", 11): "Single Leg Barbell Straight Leg Deadlift",
    ("deadlift", 12): "Single Leg Deadlift",
    ("deadlift", 13): "Single Leg Romanian Deadlift with Dumbbell",
    ("deadlift", 14): "Single Leg Stiff Leg Deadlift",
    ("deadlift", 15): "Sumo Deadlift",
    ("deadlift", 16): "Sumo Deadlift High Pull",
    ("deadlift", 17): "Trap Bar Deadlift",
    ("deadlift", 18): "Wide Grip Barbell Deadlift",
    ("deadlift", 20): "Kettlebell Deadlift",
    ("deadlift", 21): "Kettlebell Sumo Deadlift",
    ("deadlift", 23): "Romanian Deadlift",
    ("deadlift", 25): "Straight Leg Deadlift",

    # ── FLYE (9) ──────────────────────────────────────────────────────────
    ("flye",  0): "Cable Crossover",
    ("flye",  1): "Decline Dumbbell Flye",
    ("flye",  2): "Dumbbell Flye",
    ("flye",  3): "Incline Dumbbell Flye",
    ("flye",  4): "Kettlebell Flye",
    ("flye",  5): "Kneeling Rear Deltoid Cable Flye",
    ("flye",  6): "One Arm Cable Crossover",
    ("flye",  7): "Pec Dec",

    # ── HIP_RAISE (10) ────────────────────────────────────────────────────
    ("hip_raise",  0): "Barbell Hip Thrust on Floor",
    ("hip_raise",  1): "Barbell Hip Thrust with Bench",
    ("hip_raise",  2): "Bent Knee Swiss Ball Reverse Hip Raise",
    ("hip_raise",  3): "Weighted Bent Knee Swiss Ball Reverse Hip Raise",
    ("hip_raise",  4): "Bridge with Leg Extension",
    ("hip_raise",  5): "Weighted Bridge with Leg Extension",
    ("hip_raise",  6): "Clam Bridge",
    ("hip_raise",  7): "Front Kick Tabletop",
    ("hip_raise",  8): "Weighted Front Kick Tabletop",
    ("hip_raise",  9): "Hip Extension and Cross",
    ("hip_raise", 10): "Weighted Hip Extension and Cross",
    ("hip_raise", 11): "Hip Raise",
    ("hip_raise", 12): "Weighted Hip Raise",
    ("hip_raise", 13): "Hip Raise with Feet on Swiss Ball",
    ("hip_raise", 14): "Hip Raise with Head on Bosu Ball",
    ("hip_raise", 15): "Hip Raise with Knee Squeeze",
    ("hip_raise", 16): "Incline Rear Leg Extension",
    ("hip_raise", 17): "Kettlebell Swing",
    ("hip_raise", 18): "Marching Hip Raise",
    ("hip_raise", 19): "Marching Hip Raise with Feet on Swiss Ball",
    ("hip_raise", 20): "Reverse Hip Raise",
    ("hip_raise", 21): "Weighted Reverse Hip Raise",
    ("hip_raise", 22): "Single Leg Hip Raise",
    ("hip_raise", 23): "Weighted Single Leg Hip Raise",
    ("hip_raise", 24): "Single Leg Hip Raise with Foot on Bench",
    ("hip_raise", 25): "Single Leg Hip Raise with Foot on Bosu Ball",
    ("hip_raise", 26): "Single Leg Hip Raise with Foot on Foam Roller",
    ("hip_raise", 27): "Single Leg Hip Raise with Foot on Medicine Ball",
    ("hip_raise", 28): "Single Leg Hip Raise with Head on Bosu Ball",
    ("hip_raise", 29): "Weighted Marching Hip Raise",

    # ── LATERAL_RAISE (14) ────────────────────────────────────────────────
    ("lateral_raise",  0): "45 Degree Cable External Rotation",
    ("lateral_raise",  1): "Alternating Lateral Raise with Static Hold",
    ("lateral_raise",  2): "Bar Muscle Up",
    ("lateral_raise",  3): "Bent Over Lateral Raise",
    ("lateral_raise",  4): "Cable Diagonal Raise",
    ("lateral_raise",  5): "Cable Front Raise",
    ("lateral_raise",  6): "Calorie Row",
    ("lateral_raise",  7): "Combo Shoulder Raise",
    ("lateral_raise",  8): "Covered Box Jump",
    ("lateral_raise",  9): "Dumbbell Diagonal Raise",
    ("lateral_raise", 10): "Dumbbell Elevation 90",
    ("lateral_raise", 11): "Dumbbell Front Raise",
    ("lateral_raise", 12): "Dumbbell Lateral Raise",
    ("lateral_raise", 13): "Explosive Lateral Raise",
    ("lateral_raise", 14): "Front Raise",
    ("lateral_raise", 15): "Leaning Dumbbell Lateral Raise",
    ("lateral_raise", 16): "Lying Dumbbell Raise",
    ("lateral_raise", 17): "Muscle Up",
    ("lateral_raise", 18): "One Arm Cable Lateral Raise",
    ("lateral_raise", 19): "Overhand Grip Rear Lateral Raise",
    ("lateral_raise", 20): "Plate Raise",
    ("lateral_raise", 21): "Ring Dip",
    ("lateral_raise", 22): "Scapular Raise",
    ("lateral_raise", 23): "Seated Dumbbell External Rotation",
    ("lateral_raise", 24): "Seated Dumbbell Lateral Raise",
    ("lateral_raise", 25): "Side Lying Dumbbell Raise",

    # ── LEG_CURL (15) ─────────────────────────────────────────────────────
    ("leg_curl",  0): "Leg Curl",
    ("leg_curl",  1): "Weighted Leg Curl",
    ("leg_curl",  2): "Good Morning",
    ("leg_curl",  3): "Nordic Hamstring Curl",
    ("leg_curl",  4): "Seated Barbell Good Morning",
    ("leg_curl",  5): "Seated Leg Curl",
    ("leg_curl",  6): "Swiss Ball Leg Curl",
    ("leg_curl",  7): "Single Leg Curl",

    # ── LEG_RAISE (16) ────────────────────────────────────────────────────
    ("leg_raise",  0): "Hanging Knee Raise",
    ("leg_raise",  1): "Hanging Leg Raise",
    ("leg_raise",  2): "Weighted Hanging Leg Raise",
    ("leg_raise",  3): "Hanging Single Leg Raise",
    ("leg_raise",  4): "Weighted Hanging Single Leg Raise",
    ("leg_raise",  5): "Kettlebell Leg Raises",
    ("leg_raise",  6): "Leg Lowering Drill",
    ("leg_raise",  7): "Weighted Leg Lowering Drill",
    ("leg_raise",  8): "Lying Straight Leg Raise",
    ("leg_raise",  9): "Weighted Lying Straight Leg Raise",
    ("leg_raise", 10): "Medicine Ball Leg Drops",
    ("leg_raise", 11): "Quadruped Leg Raise",
    ("leg_raise", 12): "Weighted Quadruped Leg Raise",
    ("leg_raise", 13): "Reverse Leg Raise",
    ("leg_raise", 14): "Weighted Reverse Leg Raise",
    ("leg_raise", 15): "Reverse Leg Raise on Swiss Ball",
    ("leg_raise", 16): "Weighted Reverse Leg Raise on Swiss Ball",
    ("leg_raise", 17): "Single Leg Lowering Drill",
    ("leg_raise", 18): "Weighted Single Leg Lowering Drill",
    ("leg_raise", 19): "Weighted Leg Raise",
    ("leg_raise", 20): "Lying Leg Raise",

    # ── LUNGE (17) ────────────────────────────────────────────────────────
    ("lunge",  0): "Overhead Lunge",
    ("lunge",  1): "Lunge Matrix",
    ("lunge",  2): "Weighted Lunge Matrix",
    ("lunge",  3): "Alternating Barbell Forward Lunge",
    ("lunge",  4): "Alternating Dumbbell Lunge",
    ("lunge",  5): "Alternating Dumbbell Lunge with Reach",
    ("lunge",  6): "Back Foot Elevated Dumbbell Split Squat",
    ("lunge",  7): "Barbell Box Lunge",
    ("lunge",  8): "Barbell Bulgarian Split Squat",
    ("lunge",  9): "Barbell Crossover Lunge",
    ("lunge", 10): "Barbell Front Split Squat",
    ("lunge", 11): "Barbell Lunge",
    ("lunge", 12): "Barbell Reverse Lunge",
    ("lunge", 13): "Barbell Reverse Lunge with Ball Press",
    ("lunge", 14): "Barbell Side Lunge",
    ("lunge", 15): "Barbell Split Squat",
    ("lunge", 16): "Core Control Rear Lunge",
    ("lunge", 17): "Diagonal Lunge",
    ("lunge", 18): "Dumbbell Box Lunge",
    ("lunge", 19): "Dumbbell Bulgarian Split Squat",
    ("lunge", 20): "Dumbbell Crossover Lunge",
    ("lunge", 21): "Dumbbell Diagonal Lunge",
    ("lunge", 22): "Dumbbell Lunge",
    ("lunge", 23): "Dumbbell Lunge and Rotation",
    ("lunge", 24): "Dumbbell Overhead Lunge",
    ("lunge", 25): "Dumbbell Reverse Lunge",
    ("lunge", 26): "Dumbbell Side Lunge",
    ("lunge", 27): "Dumbbell Split Squat",
    ("lunge", 28): "Elevated Front Foot Barbell Split Squat",
    ("lunge", 29): "Front Foot Elevated Dumbbell Split Squat",
    ("lunge", 30): "Gunslinger Lunge",
    ("lunge", 31): "Lawnmower Lunge",
    ("lunge", 32): "Lunge",
    ("lunge", 33): "Weighted Lunge",
    ("lunge", 34): "Low Lunge with Isometric Adduction",
    ("lunge", 35): "Low Side to Side Lunge",
    ("lunge", 36): "Weighted Low Side to Side Lunge",
    ("lunge", 37): "Overhead Bulgarian Split Squat",
    ("lunge", 38): "Overhead Dumbbell Reverse Lunge",
    ("lunge", 39): "Overhead Dumbbell Split Squat",
    ("lunge", 40): "Overhead Split Squat",
    ("lunge", 41): "Prone Hip Internal Rotation",
    ("lunge", 42): "Weighted Prone Hip Internal Rotation",
    ("lunge", 43): "Rear Foot Elevated Split Squat",
    ("lunge", 44): "Reverse Lunge with Reach Back",
    ("lunge", 45): "Weighted Reverse Lunge with Reach Back",
    ("lunge", 46): "Reverse Lunge with Twist and Overhead Reach",
    ("lunge", 47): "Weighted Reverse Lunge with Twist and Overhead Reach",
    ("lunge", 48): "Reverse Sliding Box Lunge",
    ("lunge", 49): "Weighted Reverse Sliding Box Lunge",
    ("lunge", 50): "Reverse Sliding Lunge",
    ("lunge", 51): "Weighted Reverse Sliding Lunge",
    ("lunge", 52): "Runners Lunge to Balance",
    ("lunge", 53): "Weighted Runners Lunge to Balance",
    ("lunge", 54): "Shifting Side Lunge",
    ("lunge", 55): "Side and Crossover Lunge",
    ("lunge", 56): "Weighted Side and Crossover Lunge",
    ("lunge", 57): "Side Lunge",
    ("lunge", 58): "Weighted Side Lunge",
    ("lunge", 59): "Side Lunge and Press",
    ("lunge", 60): "Side Lunge Jump Off",
    ("lunge", 61): "Side Lunge Sweep",
    ("lunge", 62): "Weighted Side Lunge Sweep",
    ("lunge", 63): "Side to Side Lunge Chops",
    ("lunge", 64): "Weighted Side to Side Lunge Chops",
    ("lunge", 65): "Siff Jump Lunge",
    ("lunge", 66): "Weighted Siff Jump Lunge",
    ("lunge", 67): "Single Arm Reverse Lunge and Press",
    ("lunge", 68): "Sliding Lateral Lunge",
    ("lunge", 69): "Weighted Sliding Lateral Lunge",
    ("lunge", 70): "Walking Barbell Lunge",
    ("lunge", 71): "Walking Dumbbell Lunge",
    ("lunge", 72): "Walking Lunge",
    ("lunge", 73): "Weighted Walking Lunge",
    ("lunge", 74): "Wide Grip Overhead Barbell Split Squat",
    ("lunge", 75): "Curtsy Lunge",
    ("lunge", 76): "Bulgarian Split Squat",
    ("lunge", 77): "Split Squat",
    ("lunge", 78): "Step Up",

    # ── OLYMPIC_LIFT (18) ─────────────────────────────────────────────────
    ("olympic_lift",  0): "Barbell Hang Power Clean",
    ("olympic_lift",  1): "Barbell Hang Squat Clean",
    ("olympic_lift",  2): "Barbell Power Clean",
    ("olympic_lift",  3): "Barbell Power Snatch",
    ("olympic_lift",  4): "Barbell Squat Clean",
    ("olympic_lift",  5): "Clean and Jerk",
    ("olympic_lift",  6): "Barbell Hang Power Snatch",
    ("olympic_lift",  7): "Barbell Hang Pull",
    ("olympic_lift",  8): "Barbell High Pull",
    ("olympic_lift",  9): "Barbell Snatch",
    ("olympic_lift", 10): "Barbell Squat Snatch",
    ("olympic_lift", 11): "Clean",
    ("olympic_lift", 12): "Dumbbell Clean",
    ("olympic_lift", 13): "Dumbbell Hang Pull",
    ("olympic_lift", 14): "One Hand Dumbbell Split Snatch",
    ("olympic_lift", 15): "Push Jerk",
    ("olympic_lift", 16): "Single Arm Dumbbell Snatch",
    ("olympic_lift", 17): "Single Arm Hang Snatch",
    ("olympic_lift", 18): "Single Arm Kettlebell Snatch",
    ("olympic_lift", 19): "Split Jerk",
    ("olympic_lift", 20): "Squat Clean and Jerk",
    ("olympic_lift", 21): "Squat Jerk",
    ("olympic_lift", 22): "Tall Jerk",
    ("olympic_lift", 28): "Snatch",

    # ── PLANK (19) ────────────────────────────────────────────────────────
    ("plank",  0): "45 Degree Plank",
    ("plank",  1): "Weighted 45 Degree Plank",
    ("plank",  2): "90 Degree Static Hold",
    ("plank",  3): "Weighted 90 Degree Static Hold",
    ("plank",  4): "Bear Crawl",
    ("plank",  5): "Weighted Bear Crawl",
    ("plank",  6): "Cross Body Mountain Climber",
    ("plank",  7): "Weighted Cross Body Mountain Climber",
    ("plank",  8): "Elbow Plank Pike Jacks",
    ("plank",  9): "Weighted Elbow Plank Pike Jacks",
    ("plank", 10): "Elevated Feet Plank",
    ("plank", 11): "Weighted Elevated Feet Plank",
    ("plank", 12): "Elevator Abs",
    ("plank", 13): "Weighted Elevator Abs",
    ("plank", 14): "Extended Plank",
    ("plank", 15): "Weighted Extended Plank",
    ("plank", 16): "Full Plank Passe Twist",
    ("plank", 17): "Weighted Full Plank Passe Twist",
    ("plank", 18): "Inching Elbow Plank",
    ("plank", 19): "Weighted Inching Elbow Plank",
    ("plank", 20): "Inchworm to Side Plank",
    ("plank", 21): "Weighted Inchworm to Side Plank",
    ("plank", 22): "Kneeling Plank",
    ("plank", 23): "Weighted Kneeling Plank",
    ("plank", 24): "Kneeling Side Plank",
    ("plank", 25): "Weighted Kneeling Side Plank",
    ("plank", 26): "Mobile Plank",
    ("plank", 27): "Weighted Mobile Plank",
    ("plank", 28): "Mountain Climber",
    ("plank", 29): "Weighted Mountain Climber",
    ("plank", 30): "Mountain Climber on Sliding Discs",
    ("plank", 31): "Weighted Mountain Climber on Sliding Discs",
    ("plank", 32): "Mountain Climber with Hands on Bench",
    ("plank", 33): "Weighted Mountain Climber with Hands on Bench",
    ("plank", 34): "Mountain Climber with Hands on Swiss Ball",
    ("plank", 35): "Weighted Mountain Climber with Hands on Swiss Ball",
    ("plank", 36): "Plank",
    ("plank", 37): "Weighted Plank",
    ("plank", 38): "Plank Jacks with Feet on Sliding Discs",
    ("plank", 39): "Weighted Plank Jacks with Feet on Sliding Discs",
    ("plank", 40): "Plank Knee Twist",
    ("plank", 41): "Weighted Plank Knee Twist",
    ("plank", 42): "Plank Pike Jumps",
    ("plank", 43): "Plank with Arm Raise",
    ("plank", 44): "Weighted Plank with Arm Raise",
    ("plank", 45): "Plank with Knee to Elbow",
    ("plank", 46): "Weighted Plank with Knee to Elbow",
    ("plank", 47): "Plank with Oblique Crunch",
    ("plank", 48): "Weighted Plank with Oblique Crunch",
    ("plank", 49): "Plyometric Side Plank",
    ("plank", 50): "Weighted Plyometric Side Plank",
    ("plank", 51): "Ring Triceps Dip",
    ("plank", 52): "Weighted Ring Triceps Dip",
    ("plank", 53): "Rocking Plank",
    ("plank", 54): "Weighted Rocking Plank",
    ("plank", 55): "Side Kickthrough Plank",
    ("plank", 56): "Weighted Side Kickthrough Plank",
    ("plank", 57): "Side Plank",
    ("plank", 58): "Weighted Side Plank",
    ("plank", 59): "Side Plank and Row",
    ("plank", 60): "Weighted Side Plank and Row",
    ("plank", 61): "Side Plank Lift",
    ("plank", 62): "Weighted Side Plank Lift",
    ("plank", 63): "Side Plank with Elbow on Bosu Ball",
    ("plank", 64): "Weighted Side Plank with Elbow on Bosu Ball",
    ("plank", 65): "Side Plank with Feet on Bench",
    ("plank", 66): "Weighted Side Plank with Feet on Bench",
    ("plank", 67): "Side Plank with Knee Circle",
    ("plank", 68): "Weighted Side Plank with Knee Circle",
    ("plank", 69): "Side Plank with Knee Tuck",
    ("plank", 70): "Weighted Side Plank with Knee Tuck",
    ("plank", 71): "Side Plank with Leg Lift",
    ("plank", 72): "Weighted Side Plank with Leg Lift",
    ("plank", 73): "Side Plank with Reach Under",
    ("plank", 74): "Weighted Side Plank with Reach Under",
    ("plank", 75): "Single Leg Elevated Feet Plank",
    ("plank", 76): "Weighted Single Leg Elevated Feet Plank",
    ("plank", 77): "Single Leg Flex and Extend",
    ("plank", 78): "Weighted Single Leg Flex and Extend",
    ("plank", 79): "Single Leg Side Plank",
    ("plank", 80): "Weighted Single Leg Side Plank",
    ("plank", 81): "Spiderman Plank",
    ("plank", 82): "Weighted Spiderman Plank",
    ("plank", 83): "Straight Arm Plank",
    ("plank", 84): "Weighted Straight Arm Plank",
    ("plank", 85): "Straight Arm Plank with Shoulder Touch",
    ("plank", 86): "Weighted Straight Arm Plank with Shoulder Touch",
    ("plank", 87): "Swiss Ball Plank",
    ("plank", 88): "Weighted Swiss Ball Plank",
    ("plank", 89): "Swiss Ball Plank Leg Lift",
    ("plank", 90): "Weighted Swiss Ball Plank Leg Lift",
    ("plank", 91): "Swiss Ball Plank Leg Lift and Hold",
    ("plank", 92): "Weighted Swiss Ball Plank Leg Lift and Hold",
    ("plank", 93): "Swiss Ball Plank with Feet on Bench",
    ("plank", 94): "Weighted Swiss Ball Plank with Feet on Bench",
    ("plank", 95): "Swiss Ball Prone Jackknife",
    ("plank", 96): "Weighted Swiss Ball Prone Jackknife",
    ("plank", 97): "Swiss Ball Side Plank",
    ("plank", 98): "Weighted Swiss Ball Side Plank",
    ("plank", 99): "Three Way Plank",
    ("plank", 100): "Weighted Three Way Plank",
    ("plank", 101): "Towel Plank and Knee In",
    ("plank", 102): "Weighted Towel Plank and Knee In",
    ("plank", 103): "T Stabilization",
    ("plank", 104): "Weighted T Stabilization",
    ("plank", 105): "Turkish Get Up to Side Plank",
    ("plank", 106): "Weighted Turkish Get Up to Side Plank",
    ("plank", 107): "Two Point Plank",
    ("plank", 108): "Weighted Two Point Plank",
    ("plank", 109): "Weighted Plank",
    ("plank", 110): "Wide Stance Plank with Diagonal Arm Lift",

    # ── PULL_UP (21) ──────────────────────────────────────────────────────
    ("pull_up",  0): "Banded Pull Ups",
    ("pull_up",  1): "30 Degree Lat Pulldown",
    ("pull_up",  2): "Band Assisted Chin Up",
    ("pull_up",  3): "Close Grip Chin Up",
    ("pull_up",  4): "Weighted Close Grip Chin Up",
    ("pull_up",  5): "Close Grip Lat Pulldown",
    ("pull_up",  6): "Crossover Chin Up",
    ("pull_up",  7): "Weighted Crossover Chin Up",
    ("pull_up",  8): "Ez Bar Pullover",
    ("pull_up",  9): "Hanging Hurdle",
    ("pull_up", 10): "Kneeling Lat Pulldown",
    ("pull_up", 11): "Kneeling Underhand Grip Lat Pulldown",
    ("pull_up", 12): "Lat Pulldown",
    ("pull_up", 13): "Mixed Grip Chin Up",
    ("pull_up", 14): "Weighted Mixed Grip Chin Up",
    ("pull_up", 15): "Mixed Grip Pull Up",
    ("pull_up", 16): "Weighted Mixed Grip Pull Up",
    ("pull_up", 17): "Reverse Grip Pulldown",
    ("pull_up", 18): "Standing Cable Pullover",
    ("pull_up", 19): "Straight Arm Pulldown",
    ("pull_up", 20): "Swiss Ball Ez Bar Pullover",
    ("pull_up", 21): "Towel Pull Up",
    ("pull_up", 22): "Weighted Towel Pull Up",
    ("pull_up", 23): "Uneven Chin Up",
    ("pull_up", 24): "Weighted Pull Up",
    ("pull_up", 25): "Wide Grip Lat Pulldown",
    ("pull_up", 26): "Wide Grip Pull Up",
    ("pull_up", 27): "Weighted Wide Grip Pull Up",
    ("pull_up", 28): "Burpee Pull Up",
    ("pull_up", 29): "Weighted Burpee Pull Up",
    ("pull_up", 30): "Jumping Pull Ups",
    ("pull_up", 31): "Kipping Pull Up",
    ("pull_up", 32): "L Pull Up",
    ("pull_up", 33): "Weighted L Pull Up",
    ("pull_up", 34): "Suspended Chin Up",
    ("pull_up", 35): "Weighted Suspended Chin Up",
    ("pull_up", 36): "Pull Up",
    ("pull_up", 37): "Weighted Pull Up",
    ("pull_up", 38): "Pull Up",
    ("pull_up", 39): "Chin Up",
    ("pull_up", 40): "Neutral Grip Chin Up",
    ("pull_up", 41): "Weighted Chin Up",
    ("pull_up", 42): "Band Assisted Pull Up",
    ("pull_up", 43): "Neutral Grip Pull Up",

    # ── PUSH_UP (22) ──────────────────────────────────────────────────────
    ("push_up",  0): "Alternating Staggered Push Up",
    ("push_up",  1): "Weighted Alternating Staggered Push Up",
    ("push_up",  2): "Alternating Hands Medicine Ball Push Up",
    ("push_up",  3): "Weighted Alternating Hands Medicine Ball Push Up",
    ("push_up",  4): "Bosu Ball Push Up",
    ("push_up",  5): "Weighted Bosu Ball Push Up",
    ("push_up",  6): "Clapping Push Up",
    ("push_up",  7): "Weighted Clapping Push Up",
    ("push_up",  8): "Close Grip Medicine Ball Push Up",
    ("push_up",  9): "Weighted Close Grip Medicine Ball Push Up",
    ("push_up", 10): "Close Hands Push Up",
    ("push_up", 11): "Weighted Close Hands Push Up",
    ("push_up", 12): "Decline Push Up",
    ("push_up", 13): "Weighted Decline Push Up",
    ("push_up", 14): "Diamond Push Up",
    ("push_up", 15): "Weighted Diamond Push Up",
    ("push_up", 16): "Explosive Crossover Push Up",
    ("push_up", 17): "Weighted Explosive Crossover Push Up",
    ("push_up", 18): "Explosive Push Up",
    ("push_up", 19): "Weighted Explosive Push Up",
    ("push_up", 20): "Feet Elevated Side to Side Push Up",
    ("push_up", 21): "Weighted Feet Elevated Side to Side Push Up",
    ("push_up", 22): "Hand Release Push Up",
    ("push_up", 23): "Weighted Hand Release Push Up",
    ("push_up", 24): "Handstand Push Up",
    ("push_up", 25): "Weighted Handstand Push Up",
    ("push_up", 26): "Incline Push Up",
    ("push_up", 27): "Weighted Incline Push Up",
    ("push_up", 28): "Isometric Explosive Push Up",
    ("push_up", 29): "Weighted Isometric Explosive Push Up",
    ("push_up", 30): "Judo Push Up",
    ("push_up", 31): "Weighted Judo Push Up",
    ("push_up", 32): "Kneeling Push Up",
    ("push_up", 33): "Weighted Kneeling Push Up",
    ("push_up", 34): "Medicine Ball Chest Pass",
    ("push_up", 35): "Weighted Medicine Ball Chest Pass",
    ("push_up", 36): "Medicine Ball Push Up",
    ("push_up", 37): "Weighted Medicine Ball Push Up",
    ("push_up", 38): "One Arm Push Up",
    ("push_up", 39): "Weighted One Arm Push Up",
    ("push_up", 40): "Partial Push Up",
    ("push_up", 41): "Weighted Partial Push Up",
    ("push_up", 42): "Pike Push Up",
    ("push_up", 43): "Weighted Pike Push Up",
    ("push_up", 44): "Planche Push Up",
    ("push_up", 45): "Weighted Planche Push Up",
    ("push_up", 46): "Pull Up Plus Push Up",
    ("push_up", 47): "Weighted Pull Up Plus Push Up",
    ("push_up", 48): "Push Up",
    ("push_up", 49): "Weighted Push Up",
    ("push_up", 50): "Push Up and Row",
    ("push_up", 51): "Weighted Push Up and Row",
    ("push_up", 52): "Push Up Plus",
    ("push_up", 53): "Weighted Push Up Plus",
    ("push_up", 54): "Push Up with Feet on Swiss Ball",
    ("push_up", 55): "Weighted Push Up with Feet on Swiss Ball",
    ("push_up", 56): "Push Up with One Hand on Medicine Ball",
    ("push_up", 57): "Weighted Push Up with One Hand on Medicine Ball",
    ("push_up", 58): "Shoulder Push Up",
    ("push_up", 59): "Weighted Shoulder Push Up",
    ("push_up", 60): "Single Arm Medicine Ball Push Up",
    ("push_up", 61): "Weighted Single Arm Medicine Ball Push Up",
    ("push_up", 62): "Spiderman Push Up",
    ("push_up", 63): "Weighted Spiderman Push Up",
    ("push_up", 64): "Stacked Feet Push Up",
    ("push_up", 65): "Weighted Stacked Feet Push Up",
    ("push_up", 66): "Staggered Hands Push Up",
    ("push_up", 67): "Weighted Staggered Hands Push Up",
    ("push_up", 68): "Suspended Push Up",
    ("push_up", 69): "Weighted Suspended Push Up",
    ("push_up", 70): "Swiss Ball Push Up",
    ("push_up", 71): "Weighted Swiss Ball Push Up",
    ("push_up", 72): "Swiss Ball Push Up Plus",
    ("push_up", 73): "Weighted Swiss Ball Push Up Plus",
    ("push_up", 74): "T Push Up",
    ("push_up", 75): "Weighted T Push Up",
    ("push_up", 76): "Triple Stop Push Up",
    ("push_up", 77): "Push Up",
    ("push_up", 78): "Wide Hands Push Up",
    ("push_up", 79): "Dynamic Push Up",

    # ── ROW (23) ──────────────────────────────────────────────────────────
    ("row",  0): "Barbell Straight Leg Deadlift to Row",
    ("row",  2): "Dumbbell Row",
    ("row",  3): "Elevated Feet Inverted Row",
    ("row",  4): "Weighted Elevated Feet Inverted Row",
    ("row",  5): "Face Pull",
    ("row",  6): "Face Pull with External Rotation",
    ("row",  7): "Inverted Row",
    ("row",  8): "Weighted Inverted Row",
    ("row",  9): "Inverted Row with Feet on Swiss Ball",
    ("row", 10): "Weighted Inverted Row with Feet on Swiss Ball",
    ("row", 11): "Kettlebell Row",
    ("row", 12): "Modified Inverted Row",
    ("row", 13): "Weighted Modified Inverted Row",
    ("row", 14): "Neutral Grip Alternating Dumbbell Row",
    ("row", 15): "One Arm Bent Over Row",
    ("row", 16): "One Legged Dumbbell Row",
    ("row", 17): "Renegade Row",
    ("row", 18): "Reverse Grip Barbell Row",
    ("row", 19): "Rope Handle Cable Row",
    ("row", 20): "Seated Cable Row",
    ("row", 21): "Seated Dumbbell Row",
    ("row", 22): "Single Arm Cable Row",
    ("row", 23): "Single Arm Cable Row and Rotation",
    ("row", 24): "Single Arm Inverted Row",
    ("row", 25): "Weighted Single Arm Inverted Row",
    ("row", 26): "Single Arm Neutral Grip Dumbbell Row",
    ("row", 27): "Single Arm Neutral Grip Dumbbell Row and Rotation",
    ("row", 28): "Suspended Inverted Row",
    ("row", 29): "Weighted Suspended Inverted Row",
    ("row", 30): "T Bar Row",
    ("row", 31): "Towel Grip Inverted Row",
    ("row", 32): "Weighted Towel Grip Inverted Row",
    ("row", 33): "Underhand Grip Inverted Row",
    ("row", 34): "Weighted Underhand Grip Inverted Row",
    ("row", 35): "Wide Grip Seated Cable Row",
    ("row", 36): "Row",
    ("row", 37): "Cable Row",
    ("row", 38): "Dumbbell Bent Over Row",
    ("row", 39): "Cable One Arm Row",
    ("row", 40): "Barbell Bent Over Row",
    ("row", 41): "Pendlay Row",
    ("row", 42): "Seal Row",
    ("row", 43): "Chest Supported Row",
    ("row", 44): "Chest Supported Dumbbell Row",
    ("row", 45): "Barbell Row",
    ("row", 46): "Bent Over Row with Barbell",
    ("row", 47): "Bent Over Row with Dumbell",
    ("row", 50): "One Arm Row",
    ("row", 51): "Cable Seated Row",
    ("row", 52): "Machine Row",

    # ── SHOULDER_PRESS (24) ───────────────────────────────────────────────
    ("shoulder_press",  0): "Alternating Dumbbell Shoulder Press",
    ("shoulder_press",  1): "Arnold Press",
    ("shoulder_press",  2): "Barbell Front Squat to Push Press",
    ("shoulder_press",  3): "Barbell Push Press",
    ("shoulder_press",  4): "Barbell Shoulder Press",
    ("shoulder_press",  5): "Dead Curl Press",
    ("shoulder_press",  6): "Dumbbell Alternating Shoulder Press and Twist",
    ("shoulder_press",  7): "Dumbbell Hammer Curl to Lunge to Press",
    ("shoulder_press",  8): "Dumbbell Push Press",
    ("shoulder_press",  9): "Floor Inverted Shoulder Press",
    ("shoulder_press", 10): "Weighted Floor Inverted Shoulder Press",
    ("shoulder_press", 11): "Inverted Shoulder Press",
    ("shoulder_press", 12): "Weighted Inverted Shoulder Press",
    ("shoulder_press", 13): "One Arm Push Press",
    ("shoulder_press", 14): "Overhead Barbell Press",
    ("shoulder_press", 15): "Overhead Dumbbell Press",
    ("shoulder_press", 16): "Seated Barbell Shoulder Press",
    ("shoulder_press", 17): "Seated Dumbbell Shoulder Press",
    ("shoulder_press", 18): "Single Arm Dumbbell Shoulder Press",
    ("shoulder_press", 19): "Single Arm Step Up and Press",
    ("shoulder_press", 20): "Smith Machine Overhead Press",
    ("shoulder_press", 21): "Split Stance Hammer Curl to Press",
    ("shoulder_press", 22): "Swiss Ball Dumbbell Shoulder Press",
    ("shoulder_press", 23): "Weight Plate Front Raise",
    ("shoulder_press", 24): "Dumbbell Shoulder Press",
    ("shoulder_press", 25): "Military Press",
    ("shoulder_press", 26): "Strict Press",
    ("shoulder_press", 27): "Z Press",
    ("shoulder_press", 28): "Push Press",
    ("shoulder_press", 29): "Log Press",
    ("shoulder_press", 30): "Seated Machine Shoulder Press",

    # ── SQUAT (28) ────────────────────────────────────────────────────────
    ("squat",  0): "Leg Press",
    ("squat",  1): "Back Squat with Body Bar",
    ("squat",  2): "Back Squats",
    ("squat",  3): "Weighted Back Squats",
    ("squat",  4): "Balancing Squat",
    ("squat",  5): "Weighted Balancing Squat",
    ("squat",  6): "Barbell Back Squat",
    ("squat",  7): "Barbell Box Squat",
    ("squat",  8): "Barbell Front Squat",
    ("squat",  9): "Barbell Hack Squat",
    ("squat", 10): "Barbell Hang Squat Snatch",
    ("squat", 11): "Barbell Lateral Step Up",
    ("squat", 12): "Barbell Quarter Squat",
    ("squat", 13): "Barbell Siff Squat",
    ("squat", 14): "Barbell Squat Snatch",
    ("squat", 15): "Barbell Squat with Heels Raised",
    ("squat", 16): "Barbell Stepover",
    ("squat", 17): "Barbell Step Up",
    ("squat", 18): "Bench Squat with Rotational Chop",
    ("squat", 19): "Weighted Bench Squat with Rotational Chop",
    ("squat", 20): "Body Weight Wall Squat",
    ("squat", 21): "Weighted Body Weight Wall Squat",
    ("squat", 22): "Box Step Squat",
    ("squat", 23): "Weighted Box Step Squat",
    ("squat", 24): "Braced Squat",
    ("squat", 25): "Weighted Crossed Arm Squat",
    ("squat", 26): "Crossover Dumbbell Step Up",
    ("squat", 27): "Dumbbell Front Squat",
    ("squat", 28): "Dumbbell Split Squat",
    ("squat", 29): "Dumbbell Squat",
    ("squat", 30): "Dumbbell Squat Snatch",
    ("squat", 31): "Dumbbell Stepover",
    ("squat", 32): "Dumbbell Step Up",
    ("squat", 33): "Elevated Single Leg Squat",
    ("squat", 34): "Weighted Elevated Single Leg Squat",
    ("squat", 35): "Figure Four Squats",
    ("squat", 36): "Weighted Figure Four Squats",
    ("squat", 37): "Goblet Squat",
    ("squat", 38): "Kettlebell Squat",
    ("squat", 39): "Kettlebell Swing Overhead",
    ("squat", 40): "Kettlebell Swing with Flip to Squat",
    ("squat", 41): "Lateral Dumbbell Step Up",
    ("squat", 42): "One Legged Squat",
    ("squat", 43): "Overhead Dumbbell Squat",
    ("squat", 44): "Overhead Squat",
    ("squat", 45): "Partial Single Leg Squat",
    ("squat", 46): "Weighted Partial Single Leg Squat",
    ("squat", 47): "Pistol Squat",
    ("squat", 48): "Weighted Pistol Squat",
    ("squat", 49): "Plie Slides",
    ("squat", 50): "Weighted Plie Slides",
    ("squat", 51): "Plie Squat",
    ("squat", 52): "Weighted Plie Squat",
    ("squat", 53): "Prisoner Squat",
    ("squat", 54): "Weighted Prisoner Squat",
    ("squat", 55): "Single Leg Bench Get Up",
    ("squat", 56): "Weighted Single Leg Bench Get Up",
    ("squat", 57): "Single Leg Bench Squat",
    ("squat", 58): "Weighted Single Leg Bench Squat",
    ("squat", 59): "Single Leg Squat on Swiss Ball",
    ("squat", 60): "Weighted Single Leg Squat on Swiss Ball",
    ("squat", 61): "Squat",
    ("squat", 62): "Weighted Squat",
    ("squat", 63): "Squats with Band",
    ("squat", 64): "Staggered Squat",
    ("squat", 65): "Weighted Staggered Squat",
    ("squat", 66): "Step Up",
    ("squat", 67): "Weighted Step Up",
    ("squat", 68): "Suitcase Squats",
    ("squat", 69): "Sumo Squat",
    ("squat", 70): "Sumo Squat Slide In",
    ("squat", 71): "Weighted Sumo Squat Slide In",
    ("squat", 72): "Sumo Squat to High Pull",
    ("squat", 73): "Sumo Squat to Stand",
    ("squat", 74): "Weighted Sumo Squat to Stand",
    ("squat", 75): "Sumo Squat with Rotation",
    ("squat", 76): "Weighted Sumo Squat with Rotation",
    ("squat", 77): "Swiss Ball Body Weight Wall Squat",
    ("squat", 78): "Weighted Swiss Ball Body Weight Wall Squat",
    ("squat", 79): "Thrusters",
    ("squat", 80): "Uneven Squat",
    ("squat", 81): "Weighted Uneven Squat",
    ("squat", 82): "Waist Slimming Squat",
    ("squat", 83): "Wall Ball",
    ("squat", 84): "Wide Stance Barbell Squat",
    ("squat", 85): "Wide Stance Goblet Squat",
    ("squat", 86): "Zercher Squat",
    ("squat", 87): "KBS Squat",
    ("squat", 88): "Squat and Side Kick",
    ("squat", 89): "Squat Jumps",
    ("squat", 90): "Squat to Stand",
    ("squat", 91): "Squat Twist",
    ("squat", 92): "Star Jump",
    ("squat", 93): "Wall Squat",
    ("squat", 94): "Box Squat",
    ("squat", 95): "High Bar Squat",
    ("squat", 96): "Low Bar Squat",
    ("squat", 97): "Pause Squat",
    ("squat", 98): "Safety Bar Squat",
    ("squat", 99): "Front Squat",
    ("squat", 100): "Air Squat",
    ("squat", 101): "Dumbbell Thrusters",
    ("squat", 102): "Overhead Barbell Squat",

    # ── TRICEPS_EXTENSION (30) ────────────────────────────────────────────
    ("triceps_extension",  0): "Bench Dip",
    ("triceps_extension",  1): "Weighted Bench Dip",
    ("triceps_extension",  2): "Body Weight Dip",
    ("triceps_extension",  3): "Cable Kickback",
    ("triceps_extension",  4): "Cable Lying Triceps Extension",
    ("triceps_extension",  5): "Cable Overhead Triceps Extension",
    ("triceps_extension",  6): "Dumbbell Kickback",
    ("triceps_extension",  7): "Dumbbell Lying Triceps Extension",
    ("triceps_extension",  8): "Ez Bar Overhead Triceps Extension",
    ("triceps_extension",  9): "Incline Ez Bar Lying Triceps Extension",
    ("triceps_extension", 10): "Lying Dumbbell Pullover to Extension",
    ("triceps_extension", 11): "Lying Ez Bar Triceps Extension",
    ("triceps_extension", 12): "Lying Triceps Extension to Close Grip Bench Press",
    ("triceps_extension", 13): "Overhead Dumbbell Triceps Extension",
    ("triceps_extension", 14): "Reclining Triceps Press",
    ("triceps_extension", 15): "Reverse Grip Pressdown",
    ("triceps_extension", 16): "Reverse Grip Triceps Pressdown",
    ("triceps_extension", 17): "Rope Overhead Triceps Extension",
    ("triceps_extension", 18): "Seated Barbell Overhead Triceps Extension",
    ("triceps_extension", 19): "Rope Pressdown",
    ("triceps_extension", 20): "Seated Dumbbell Overhead Triceps Extension",
    ("triceps_extension", 21): "Seated Ez Bar Overhead Triceps Extension",
    ("triceps_extension", 22): "Seated Single Arm Overhead Dumbbell Extension",
    ("triceps_extension", 23): "Single Arm Dumbbell Overhead Triceps Extension",
    ("triceps_extension", 24): "Single Dumbbell Seated Overhead Triceps Extension",
    ("triceps_extension", 25): "Single Leg Bench Dip and Kick",
    ("triceps_extension", 26): "Weighted Single Leg Bench Dip and Kick",
    ("triceps_extension", 27): "Single Leg Dip",
    ("triceps_extension", 28): "Weighted Single Leg Dip",
    ("triceps_extension", 29): "Static Lying Triceps Extension",
    ("triceps_extension", 30): "Suspended Dip",
    ("triceps_extension", 31): "Narrow Grip Push Up",
    ("triceps_extension", 32): "Weighted Narrow Grip Push Up",
    ("triceps_extension", 33): "Parallel Bar Dip",
    ("triceps_extension", 34): "Weighted Parallel Bar Dip",
    ("triceps_extension", 35): "Ring Dip",
    ("triceps_extension", 36): "Weighted Ring Dip",
    ("triceps_extension", 37): "Rip Fence Dip",
    ("triceps_extension", 38): "Weighted Rip Fence Dip",
    ("triceps_extension", 39): "Triceps Pressdown",
    ("triceps_extension", 40): "Skullcrusher",
    ("triceps_extension", 41): "Dip",
    ("triceps_extension", 42): "Cable Triceps Pushdown",
    ("triceps_extension", 43): "Overhead Triceps Extension",
    ("triceps_extension", 44): "Lying Triceps Extension",
    ("triceps_extension", 45): "Triceps Extension",

    # ── SHRUG (26) ────────────────────────────────────────────────────────
    ("shrug",  0): "Barbell Shrug",
    ("shrug",  1): "Cable Shrug",
    ("shrug",  2): "Dumbbell Shrug",
    ("shrug",  3): "Incline Dumbbell Shrug",
    ("shrug",  4): "Reverse Barbell Shrug",
    ("shrug",  5): "Reverse Shrug",
    ("shrug",  6): "Scaption and Shrug",
    ("shrug",  7): "Scapular Retraction",
    ("shrug",  8): "Seated Barbell Shrug",
    ("shrug",  9): "Shrug",
    ("shrug", 10): "Single Arm Dumbbell Shrug",
    ("shrug", 11): "Smith Machine Shrug",
    ("shrug", 12): "Trap Bar Shrug",

    # ── SIT_UP (27) ───────────────────────────────────────────────────────
    ("sit_up",  0): "Alternating Sit Up",
    ("sit_up",  1): "Weighted Alternating Sit Up",
    ("sit_up",  2): "Bent Knee V Up",
    ("sit_up",  3): "Weighted Bent Knee V Up",
    ("sit_up",  4): "Butterfly Sit Up",
    ("sit_up",  5): "Weighted Butterfly Sit Up",
    ("sit_up",  6): "Cross Punch Roll Up",
    ("sit_up",  7): "Weighted Cross Punch Roll Up",
    ("sit_up",  8): "Crossed Arms Sit Up",
    ("sit_up",  9): "Weighted Crossed Arms Sit Up",
    ("sit_up", 10): "Get Up Sit Up",
    ("sit_up", 11): "Weighted Get Up Sit Up",
    ("sit_up", 12): "Hovering Sit Up",
    ("sit_up", 13): "Weighted Hovering Sit Up",
    ("sit_up", 14): "Kettlebell Sit Up",
    ("sit_up", 15): "Medicine Ball Alternating V Up",
    ("sit_up", 16): "Medicine Ball Sit Up",
    ("sit_up", 17): "Medicine Ball V Up",
    ("sit_up", 18): "Modified Sit Up",
    ("sit_up", 19): "Negative Sit Up",
    ("sit_up", 20): "One Arm Full Sit Up",
    ("sit_up", 21): "Reclining Circle",
    ("sit_up", 22): "Weighted Reclining Circle",
    ("sit_up", 23): "Reverse Curl Up",
    ("sit_up", 24): "Weighted Reverse Curl Up",
    ("sit_up", 25): "Single Leg Swiss Ball Jackknife",
    ("sit_up", 26): "Weighted Single Leg Swiss Ball Jackknife",
    ("sit_up", 27): "The Teaser",
    ("sit_up", 28): "Weighted The Teaser",
    ("sit_up", 29): "Three Part Roll Down",
    ("sit_up", 30): "Weighted Three Part Roll Down",
    ("sit_up", 31): "V Up",
    ("sit_up", 32): "Weighted V Up",
    ("sit_up", 33): "Weighted Russian Twist on Swiss Ball",
    ("sit_up", 34): "Weighted Sit Up",
    ("sit_up", 35): "X Abs",
    ("sit_up", 36): "Weighted X Abs",
    ("sit_up", 37): "Sit Up",

    # ── TOTAL_BODY (29) ───────────────────────────────────────────────────
    ("total_body",  0): "Burpee",
    ("total_body",  1): "Weighted Burpee",
    ("total_body",  2): "Burpee Box Jump",
    ("total_body",  3): "Weighted Burpee Box Jump",
    ("total_body",  4): "High Pull",
    ("total_body",  5): "Land Mine Rotation",
    ("total_body",  6): "Weighted Land Mine Rotation",
    ("total_body",  7): "Man Makers",
    ("total_body",  8): "One Arm Burpee",
    ("total_body",  9): "Push Up to 45 Degree Row",
    ("total_body", 10): "Push Up and Row",
    ("total_body", 11): "Weighted Push Up and Row",
    ("total_body", 12): "T30 Multi Planar Row",
    ("total_body", 13): "Weighted T30 Multi Planar Row",

    # ── HIP_STABILITY (11) ────────────────────────────────────────────────
    ("hip_stability",  0): "Band Side Lying Leg Raise",
    ("hip_stability",  2): "Fire Hydrant Kicks",
    ("hip_stability",  4): "Hip Circles",
    ("hip_stability",  6): "Hip Extension with Band",
    ("hip_stability",  9): "Lateral Band Walk",
    ("hip_stability", 10): "Lateral Step Over",
    ("hip_stability", 13): "Monster Walk",
    ("hip_stability", 14): "Penguin Walk",
    ("hip_stability", 15): "Quadruped Hip Extension",
    ("hip_stability", 17): "Seated Clam",
    ("hip_stability", 18): "Side Lying Clam",
    ("hip_stability", 22): "Side Lying Leg Raise",
    ("hip_stability", 28): "Standing Hip Extension",
    ("hip_stability", 31): "Donkey Kick",
    ("hip_stability", 32): "Fire Hydrant",
}


# FIT exercise_category enum integer → canonical snake_case name.
# fitdecode returns raw ints when it cannot decode the enum (e.g. the field
# definition uses a type that wasn't in its profile).  Source: Garmin FIT SDK
# Profile 21.205 and extended Garmin Connect firmware additions.
_CATEGORY_ID: dict[int, str] = {
    0:  "bench_press",
    1:  "calf_raise",
    2:  "cardio",
    3:  "carry",
    4:  "chop",
    5:  "core",
    6:  "crunch",
    7:  "curl",
    8:  "deadlift",
    9:  "flye",
    10: "hip_raise",
    11: "hip_stability",
    12: "hip_swing",
    13: "hyperextension",
    14: "lateral_raise",
    15: "leg_curl",
    16: "leg_raise",
    17: "lunge",
    18: "olympic_lift",
    19: "plank",
    20: "plyo",
    21: "pull_up",
    22: "push_up",
    23: "row",
    24: "shoulder_press",
    25: "shoulder_stability",
    26: "shrug",
    27: "sit_up",
    28: "squat",
    29: "total_body",
    30: "triceps_extension",
    31: "warm_up",
    32: "run",
    # Garmin firmware extensions (Profile ≥ 21.16x)
    33: "unknown",
    34: "hip_hinge",
    35: "pull",
    36: "push",
}
