// SPDX-FileCopyrightText: 2026 Hawk Fugagli
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED FILE — DO NOT EDIT.
//
// Source: spec/muscle_groups.yaml
// Regenerate: python3 spec/codegen.py
//
// Edits here are silently discarded on the next codegen run. The tables are
// shared across the Python backend, the JS frontend, and the Kotlin mobile
// core precisely so they cannot drift apart — change the spec, not this.

package com.tracks.core.spec

internal val CATEGORY_MUSCLES: Map<String, MuscleMap> = mapOf(
    "bench_press" to MuscleMap(primary = listOf("chest"), secondary = listOf("front_delts", "triceps")),
    "calf_raise" to MuscleMap(primary = listOf("calves_front", "calves_back"), secondary = listOf()),
    "cardio" to MuscleMap(primary = listOf(), secondary = listOf()),
    "carry" to MuscleMap(primary = listOf("forearms", "traps"), secondary = listOf("abs", "obliques", "lower_back", "glutes")),
    "chop" to MuscleMap(primary = listOf("obliques"), secondary = listOf("abs", "side_delts", "rear_delts")),
    "core" to MuscleMap(primary = listOf("abs", "obliques"), secondary = listOf("lower_back")),
    "crunch" to MuscleMap(primary = listOf("abs"), secondary = listOf("obliques", "hip_flexors")),
    "curl" to MuscleMap(primary = listOf("biceps"), secondary = listOf("forearms")),
    "deadlift" to MuscleMap(primary = listOf("hamstrings", "glutes", "lower_back"), secondary = listOf("traps", "forearms", "lats", "quads", "adductors")),
    "flye" to MuscleMap(primary = listOf("chest"), secondary = listOf("front_delts")),
    "hip_raise" to MuscleMap(primary = listOf("glutes"), secondary = listOf("hamstrings", "lower_back")),
    "hip_stability" to MuscleMap(primary = listOf("glutes"), secondary = listOf("obliques", "hamstrings")),
    "hip_swing" to MuscleMap(primary = listOf("glutes", "hamstrings"), secondary = listOf("lower_back", "abs")),
    "hyperextension" to MuscleMap(primary = listOf("lower_back"), secondary = listOf("glutes", "hamstrings")),
    "lateral_raise" to MuscleMap(primary = listOf("side_delts"), secondary = listOf("traps", "rear_delts")),
    "leg_curl" to MuscleMap(primary = listOf("hamstrings"), secondary = listOf("calves_back")),
    "leg_raise" to MuscleMap(primary = listOf("abs", "hip_flexors"), secondary = listOf("obliques")),
    "lunge" to MuscleMap(primary = listOf("quads", "glutes"), secondary = listOf("hamstrings", "calves_front", "calves_back", "adductors")),
    "olympic_lift" to MuscleMap(primary = listOf("quads", "glutes", "traps"), secondary = listOf("lower_back", "front_delts", "side_delts", "forearms", "hamstrings")),
    "plank" to MuscleMap(primary = listOf("abs"), secondary = listOf("obliques", "front_delts", "lower_back")),
    "plyo" to MuscleMap(primary = listOf("quads", "calves_front", "calves_back"), secondary = listOf("glutes", "hamstrings")),
    "pull_up" to MuscleMap(primary = listOf("lats"), secondary = listOf("biceps", "rear_delts", "mid_back", "forearms")),
    "push_up" to MuscleMap(primary = listOf("chest", "triceps"), secondary = listOf("front_delts", "abs")),
    "row" to MuscleMap(primary = listOf("lats", "mid_back"), secondary = listOf("rear_delts", "biceps", "traps", "forearms")),
    "shoulder_press" to MuscleMap(primary = listOf("front_delts", "side_delts"), secondary = listOf("triceps", "traps")),
    "shoulder_stability" to MuscleMap(primary = listOf("rear_delts"), secondary = listOf("traps")),
    "shrug" to MuscleMap(primary = listOf("traps"), secondary = listOf("forearms")),
    "sit_up" to MuscleMap(primary = listOf("abs"), secondary = listOf("hip_flexors", "obliques")),
    "squat" to MuscleMap(primary = listOf("quads", "glutes"), secondary = listOf("hamstrings", "lower_back", "calves_front", "calves_back", "adductors")),
    "total_body" to MuscleMap(primary = listOf("chest", "lats", "quads", "glutes"), secondary = listOf("abs", "shoulders", "biceps", "triceps", "hamstrings")),
    "triceps_extension" to MuscleMap(primary = listOf("triceps"), secondary = listOf()),
    "warm_up" to MuscleMap(primary = listOf(), secondary = listOf()),
    "run" to MuscleMap(primary = listOf(), secondary = listOf()),
    "hip_hinge" to MuscleMap(primary = listOf("glutes", "hamstrings"), secondary = listOf("lower_back")),
    "push" to MuscleMap(primary = listOf("chest", "front_delts", "triceps"), secondary = listOf("side_delts", "abs")),
    "pull" to MuscleMap(primary = listOf("lats", "biceps"), secondary = listOf("rear_delts", "mid_back", "forearms")),
)

internal val MUSCLE_LABELS: Map<String, String> = mapOf(
    "chest" to "Chest",
    "front_delts" to "Front Deltoids",
    "side_delts" to "Side Deltoids",
    "rear_delts" to "Rear Deltoids",
    "biceps" to "Biceps",
    "triceps" to "Triceps",
    "forearms" to "Forearms",
    "traps" to "Trapezius",
    "lats" to "Lats",
    "mid_back" to "Mid Back",
    "lower_back" to "Lower Back",
    "abs" to "Abs",
    "obliques" to "Obliques",
    "hip_flexors" to "Hip Flexors",
    "glutes" to "Glutes",
    "quads" to "Quads",
    "hamstrings" to "Hamstrings",
    "calves_front" to "Calves (Front)",
    "calves_back" to "Calves",
    "adductors" to "Adductors",
    "neck" to "Neck",
    "core" to "Core",
    "upper_back" to "Upper Back",
    "achilles" to "Achilles",
    "back" to "Back",
    "brachialis" to "Brachialis",
    "calves" to "Calves",
    "feet" to "Feet",
    "full_body" to "Full Body",
    "groin" to "Groin",
    "hands" to "Hands",
    "hip_abductors" to "Hip Abductors",
    "hip_adductors" to "Hip Adductors",
    "hip_external_rotators" to "Hip External Rotators",
    "hips" to "Hips",
    "intercostals" to "Intercostals",
    "pec_minor" to "Pec Minor",
    "shoulders" to "Shoulders",
    "spinal_erectors" to "Spinal Erectors",
    "thoracic_spine" to "Thoracic Spine",
    "wrists" to "Wrists",
)

internal val CATEGORY_LABELS: Map<String, String> = mapOf(
    "bench_press" to "Bench Press",
    "calf_raise" to "Calf Raise",
    "cardio" to "Cardio",
    "carry" to "Carry",
    "chop" to "Chop",
    "core" to "Core",
    "crunch" to "Crunch",
    "curl" to "Curl",
    "deadlift" to "Deadlift",
    "flye" to "Flye",
    "hip_raise" to "Hip Raise",
    "hip_stability" to "Hip Stability",
    "hip_swing" to "Hip Swing",
    "hyperextension" to "Hyperextension",
    "lateral_raise" to "Lateral Raise",
    "leg_curl" to "Leg Curl",
    "leg_raise" to "Leg Raise",
    "lunge" to "Lunge",
    "olympic_lift" to "Olympic Lift",
    "plank" to "Plank",
    "plyo" to "Plyometric",
    "pull_up" to "Pull-Up",
    "push_up" to "Push-Up",
    "row" to "Row",
    "shoulder_press" to "Shoulder Press",
    "shoulder_stability" to "Shoulder Stability",
    "shrug" to "Shrug",
    "sit_up" to "Sit-Up",
    "squat" to "Squat",
    "total_body" to "Total Body",
    "triceps_extension" to "Triceps Extension",
    "warm_up" to "Warm-Up",
    "run" to "Run",
)

public val BODY_VIEWER_REGIONS: Map<String, BodyRegion> = mapOf(
    "chest_l" to BodyRegion(muscle = "chest", slug = "chest", view = "front"),
    "chest_r" to BodyRegion(muscle = "chest", slug = "chest", view = "front"),
    "front_delts_l" to BodyRegion(muscle = "front_delts", slug = "deltoids", view = "front"),
    "front_delts_r" to BodyRegion(muscle = "front_delts", slug = "deltoids", view = "front"),
    "side_delts_l" to BodyRegion(muscle = "side_delts", slug = "deltoids", view = "front"),
    "side_delts_r" to BodyRegion(muscle = "side_delts", slug = "deltoids", view = "front"),
    "biceps_l" to BodyRegion(muscle = "biceps", slug = "biceps", view = "front"),
    "biceps_r" to BodyRegion(muscle = "biceps", slug = "biceps", view = "front"),
    "forearms_l" to BodyRegion(muscle = "forearms", slug = "forearm", view = "front"),
    "forearms_r" to BodyRegion(muscle = "forearms", slug = "forearm", view = "front"),
    "abs" to BodyRegion(muscle = "abs", slug = "abs", view = "front"),
    "obliques_l" to BodyRegion(muscle = "obliques", slug = "obliques", view = "front"),
    "obliques_r" to BodyRegion(muscle = "obliques", slug = "obliques", view = "front"),
    "hip_flexors_l" to BodyRegion(muscle = "hip_flexors", slug = "quadriceps", view = "front"),
    "hip_flexors_r" to BodyRegion(muscle = "hip_flexors", slug = "quadriceps", view = "front"),
    "quads_l" to BodyRegion(muscle = "quads", slug = "quadriceps", view = "front"),
    "quads_r" to BodyRegion(muscle = "quads", slug = "quadriceps", view = "front"),
    "calves_front_l" to BodyRegion(muscle = "calves_front", slug = "tibialis", view = "front"),
    "calves_front_r" to BodyRegion(muscle = "calves_front", slug = "tibialis", view = "front"),
    "neck_l" to BodyRegion(muscle = "neck", slug = "neck", view = "front"),
    "neck_r" to BodyRegion(muscle = "neck", slug = "neck", view = "front"),
    "ankles_l" to BodyRegion(muscle = "calves_front", slug = "ankles", view = "front"),
    "ankles_r" to BodyRegion(muscle = "calves_front", slug = "ankles", view = "front"),
    "hands_l" to BodyRegion(muscle = "hands", slug = "hands", view = "front"),
    "hands_r" to BodyRegion(muscle = "hands", slug = "hands", view = "front"),
    "feet_l" to BodyRegion(muscle = "feet", slug = "feet", view = "front"),
    "feet_r" to BodyRegion(muscle = "feet", slug = "feet", view = "front"),
    "traps" to BodyRegion(muscle = "traps", slug = "trapezius", view = "back"),
    "rear_delts_l" to BodyRegion(muscle = "rear_delts", slug = "deltoids", view = "back"),
    "rear_delts_r" to BodyRegion(muscle = "rear_delts", slug = "deltoids", view = "back"),
    "mid_back" to BodyRegion(muscle = "mid_back", slug = "upper-back", view = "back"),
    "lats_l" to BodyRegion(muscle = "lats", slug = "upper-back", view = "back"),
    "lats_r" to BodyRegion(muscle = "lats", slug = "upper-back", view = "back"),
    "triceps_l" to BodyRegion(muscle = "triceps", slug = "triceps", view = "back"),
    "triceps_r" to BodyRegion(muscle = "triceps", slug = "triceps", view = "back"),
    "lower_back" to BodyRegion(muscle = "lower_back", slug = "lower-back", view = "back"),
    "glutes_l" to BodyRegion(muscle = "glutes", slug = "gluteal", view = "back"),
    "glutes_r" to BodyRegion(muscle = "glutes", slug = "gluteal", view = "back"),
    "hamstrings_l" to BodyRegion(muscle = "hamstrings", slug = "hamstring", view = "back"),
    "hamstrings_r" to BodyRegion(muscle = "hamstrings", slug = "hamstring", view = "back"),
    "calves_back_l" to BodyRegion(muscle = "calves_back", slug = "calves", view = "back"),
    "calves_back_r" to BodyRegion(muscle = "calves_back", slug = "calves", view = "back"),
    "adductors_l" to BodyRegion(muscle = "adductors", slug = "adductors", view = "front"),
    "adductors_r" to BodyRegion(muscle = "adductors", slug = "adductors", view = "front"),
    "adductors_bl" to BodyRegion(muscle = "adductors", slug = "adductors", view = "back"),
    "adductors_br" to BodyRegion(muscle = "adductors", slug = "adductors", view = "back"),
    "neck_bl" to BodyRegion(muscle = "neck", slug = "neck", view = "back"),
    "neck_br" to BodyRegion(muscle = "neck", slug = "neck", view = "back"),
)
