#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate per-language data modules from the specs in this directory.

## Why this exists

Tracks now has three implementations of the same domain: Python on the server,
JavaScript in the web app, and Kotlin in the mobile core. The algorithms differ
by language, but the *tables* they operate on — which FIT sport maps to which
type, where a heart-rate zone starts, what counts as a good TSB — are the same
facts, and that is where drift actually happens. A regex reordered in one file
and not the others produces two clients that disagree about what a ride is,
with nothing failing to announce it.

So the tables live in YAML here and get generated into each language. Editing a
generated file is pointless: the next codegen run overwrites it.

## What is NOT generated

Only data. The evaluators that walk these rules are small, hand-written, and
idiomatic in each language — string-templating three of them would be far worse
to maintain than the thing it prevents. They are kept honest by golden
fixtures instead (spec/fixtures/, generated by make_fixtures.py), which every
language's test suite runs against the same expected outputs.

Usage:
    python3 spec/codegen.py           # write the generated modules
    python3 spec/codegen.py --check   # exit 1 if anything is out of date (CI)
"""

import json
import pprint
import sys
from pathlib import Path

import yaml

SPEC_DIR = Path(__file__).resolve().parent
ROOT = SPEC_DIR.parent

# Emitted into every generated file. The SPDX lines come first so the repo stays
# REUSE-compliant without the header sweep having to special-case build output
# (a stamp added there would be erased by the next codegen run).
BANNER_LINES = [
    "SPDX-FileCopyrightText: 2026 Hawk Fugagli",
    "SPDX-License-Identifier: AGPL-3.0-or-later",
    "",
    "GENERATED FILE — DO NOT EDIT.",
    "",
    "Source: spec/sport_taxonomy.yaml",
    "Regenerate: python3 spec/codegen.py",
    "",
    "Edits here are silently discarded on the next codegen run. The tables are",
    "shared across the Python backend, the JS frontend, and the Kotlin mobile",
    "core precisely so they cannot drift apart — change the spec, not this.",
]


def _banner(comment: str) -> str:
    return "\n".join(f"{comment} {line}".rstrip() for line in BANNER_LINES)


def load_spec(name: str) -> dict:
    with open(SPEC_DIR / f"{name}.yaml") as fh:
        return yaml.safe_load(fh)


# ── Sport taxonomy ───────────────────────────────────────────────────────────

def _normalise_rules(spec: dict) -> list[dict]:
    """Strip the prose fields so generated output carries only what executes.

    `why:` is documentation for whoever edits the spec. Emitting it into three
    languages would just be three copies of a comment nobody reads at the call
    site, and it would make the generated diffs noisy for wording changes.
    """
    rules = []
    for rule in spec["rules"]:
        out = {"type": rule["type"], "any": rule["any"]}
        if rule.get("none"):
            out["none"] = rule["none"]
        rules.append(out)
    return rules


def _payload(spec: dict) -> dict:
    return {
        "types": spec["types"],
        "fallback": spec["fallback"],
        "rules": _normalise_rules(spec),
    }


def gen_sport_taxonomy_python(spec: dict) -> tuple[Path, str]:
    # JSON output is valid Python here: the spec is strings and lists all the
    # way down, with no booleans, nulls, or floats to differ on.
    data = _payload(spec)
    src = (
        '"""\n' + "\n".join(BANNER_LINES) + '\n"""\n\n'
        f"SPORT_TYPES = {json.dumps(data['types'], indent=4)}\n\n"
        f"FALLBACK = {json.dumps(data['fallback'])}\n\n"
        f"RULES = {json.dumps(data['rules'], indent=4)}\n"
    )
    return ROOT / "backend/app/spec/sport_taxonomy.py", src


def gen_sport_taxonomy_js(spec: dict) -> tuple[Path, str]:
    data = _payload(spec)
    src = (
        _banner("//") + "\n\n"
        f"export const SPORT_TYPE_LIST = {json.dumps(data['types'], indent=2)};\n\n"
        f"export const FALLBACK = {json.dumps(data['fallback'])};\n\n"
        f"export const RULES = {json.dumps(data['rules'], indent=2)};\n"
    )
    return ROOT / "frontend/src/spec/sportTaxonomy.js", src


def _kotlin_conditions(entries: list) -> str:
    parts = []
    for entry in entries:
        if "all" in entry:
            inner = ", ".join(_kotlin_condition(c) for c in entry["all"])
            parts.append(f"Entry.All(listOf({inner}))")
        else:
            parts.append(f"Entry.One({_kotlin_condition(entry)})")
    return "listOf(" + ", ".join(parts) + ")"


def _kotlin_condition(cond: dict) -> str:
    field = cond["field"]
    if "equals" in cond:
        return f"Condition(Field.{field.upper()}, eq = {_kstr(cond['equals'])})"
    return f"Condition(Field.{field.upper()}, matches = {_kstr(cond['matches'])})"


def gen_sport_taxonomy_kotlin(spec: dict) -> tuple[Path, str]:
    data = _payload(spec)
    rules = []
    for rule in data["rules"]:
        none = (
            f", none = {_kotlin_conditions(rule['none'])}"
            if rule.get("none") else ""
        )
        rules.append(
            f"    Rule({_kstr(rule['type'])}, any = {_kotlin_conditions(rule['any'])}{none}),"
        )
    types = ",\n".join(f"    {_kstr(t)}" for t in data["types"])
    src = (
        _banner("//") + "\n\n"
        "package com.tracks.core.spec\n\n"
        "internal val SPORT_TYPE_LIST: List<String> = listOf(\n"
        f"{types},\n)\n\n"
        f"internal const val FALLBACK: String = {_kstr(data['fallback'])}\n\n"
        "internal val RULES: List<Rule> = listOf(\n"
        + "\n".join(rules)
        + "\n)\n"
    )
    return (
        ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/spec/SportTaxonomyData.kt",
        src,
    )


# ── Zones ────────────────────────────────────────────────────────────────────

def _zone_payload(spec: dict) -> dict:
    """Drop the prose (`why`), keep `source` — an attribution belongs next to
    the numbers it justifies, and a reader of the generated table has no other
    way to find out where 0.85 came from."""
    def model(m: dict) -> dict:
        return {
            "basis": m["basis"],
            "source": m["source"],
            "zones": m["zones"],
        }

    return {
        "hr_models": {k: model(v) for k, v in spec["hr_models"].items()},
        "power_models": {k: model(v) for k, v in spec["power_models"].items()},
        "tsb_bands": {
            "source": spec["tsb_bands"]["source"],
            "bands": spec["tsb_bands"]["bands"],
            "unknown": spec["tsb_bands"]["unknown"],
        },
    }


def _pyliteral(value) -> str:
    """A Python literal for the generated module.

    pprint rather than json.dumps because the zone tables carry `null` for
    unbounded maxima, and JSON's spelling of that is not Python's. Patching the
    text afterwards would corrupt any string that happened to contain ": null".
    """
    return pprint.pformat(value, indent=4, width=88, sort_dicts=False)


def gen_zones_python(spec: dict) -> tuple[Path, str]:
    data = _zone_payload(spec)
    src = (
        '"""\n' + "\n".join(BANNER_LINES).replace(
            "spec/sport_taxonomy.yaml", "spec/zones.yaml") + '\n"""\n\n'
        f"HR_MODELS = {_pyliteral(data['hr_models'])}\n\n"
        f"POWER_MODELS = {_pyliteral(data['power_models'])}\n\n"
        f"TSB_BANDS = {_pyliteral(data['tsb_bands'])}\n"
    )
    return ROOT / "backend/app/spec/zones.py", src


def gen_zones_js(spec: dict) -> tuple[Path, str]:
    data = _zone_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/zones.yaml")
    src = (
        banner + "\n\n"
        f"export const HR_MODELS = {json.dumps(data['hr_models'], indent=2)};\n\n"
        f"export const POWER_MODELS = {json.dumps(data['power_models'], indent=2)};\n\n"
        f"export const TSB_BANDS = {json.dumps(data['tsb_bands'], indent=2)};\n"
    )
    return ROOT / "frontend/src/spec/zones.js", src


def _kstr(value: str) -> str:
    """A Kotlin string literal.

    JSON escaping covers quotes and backslashes identically, but Kotlin also
    interpolates `$`, so that has to be escaped too — otherwise a source
    attribution containing a dollar sign becomes a compile error in a generated
    file nobody is reading.
    """
    return json.dumps(value).replace("$", "\\$")


def _kotlin_zone(z: dict) -> str:
    max_pct = "null" if z["max_pct"] is None else str(z["max_pct"])
    color = f", color = {_kstr(z['color'])}" if z.get("color") else ""
    return (
        f"Zone({z['number']}, {_kstr(z['name'])}, {_kstr(z['description'])}, "
        f"{z['min_pct']}, {max_pct}{color})"
    )


def _kotlin_model(name: str, m: dict) -> str:
    zones = ",\n            ".join(_kotlin_zone(z) for z in m["zones"])
    return (
        f"    {_kstr(name)} to ZoneModel(\n"
        f"        basis = {_kstr(m['basis'])},\n"
        f"        source = {_kstr(m['source'].rstrip())},\n"
        f"        zones = listOf(\n            {zones},\n        ),\n"
        "    ),"
    )


def gen_zones_kotlin(spec: dict) -> tuple[Path, str]:
    data = _zone_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/zones.yaml")

    hr = "\n".join(_kotlin_model(k, v) for k, v in data["hr_models"].items())
    power = "\n".join(_kotlin_model(k, v) for k, v in data["power_models"].items())

    bands = []
    for b in data["tsb_bands"]["bands"]:
        lo = "null" if b["min"] is None else str(b["min"])
        hi = "null" if b["max"] is None else str(b["max"])
        bands.append(
            f"    TsbBand({_kstr(b['key'])}, {_kstr(b['label'])}, {lo}, {hi}, "
            f"{_kstr(b['color'])}, {_kstr(b['bg'])}, {_kstr(b['desc'])}),"
        )

    src = (
        banner + "\n\n"
        "package com.tracks.core.spec\n\n"
        f"internal val HR_MODELS: Map<String, ZoneModel> = mapOf(\n{hr}\n)\n\n"
        f"internal val POWER_MODELS: Map<String, ZoneModel> = mapOf(\n{power}\n)\n\n"
        "internal val TSB_BANDS: List<TsbBand> = listOf(\n"
        + "\n".join(bands)
        + "\n)\n\n"
        "internal const val TSB_UNKNOWN_BAND: String = "
        + _kstr(data["tsb_bands"]["unknown"]) + "\n"
    )
    return ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/spec/ZonesData.kt", src


# ── Muscle groups ────────────────────────────────────────────────────────────

def _muscle_groups_payload(spec: dict) -> dict:
    return {
        "category_muscles": spec["category_muscles"],
        "muscle_labels": spec["muscle_labels"],
        "category_labels": spec["category_labels"],
        # Not emitted for Python: the backend computes activation per muscle
        # key and has no opinion about where a shape sits on a diagram. Only the
        # two clients that draw a body need this.
        "body_viewer_regions": spec["body_viewer"]["regions"],
    }


def gen_muscle_groups_python(spec: dict) -> tuple[Path, str]:
    data = _muscle_groups_payload(spec)
    banner = "\n".join(BANNER_LINES).replace(
        "spec/sport_taxonomy.yaml", "spec/muscle_groups.yaml")
    src = (
        '"""\n' + banner + '\n"""\n\n'
        f"CATEGORY_MUSCLES = {json.dumps(data['category_muscles'], indent=4)}\n\n"
        f"MUSCLE_LABELS = {json.dumps(data['muscle_labels'], indent=4)}\n\n"
        f"CATEGORY_LABELS = {json.dumps(data['category_labels'], indent=4)}\n"
    )
    return ROOT / "backend/app/spec/muscle_groups.py", src


def gen_muscle_groups_js(spec: dict) -> tuple[Path, str]:
    data = _muscle_groups_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/muscle_groups.yaml")
    src = (
        banner + "\n\n"
        f"export const CATEGORY_MUSCLES = {json.dumps(data['category_muscles'], indent=2)};\n\n"
        f"export const MUSCLE_LABELS = {json.dumps(data['muscle_labels'], indent=2)};\n\n"
        f"export const CATEGORY_LABELS = {json.dumps(data['category_labels'], indent=2)};\n\n"
        "export const BODY_VIEWER_REGIONS = "
        f"{json.dumps(data['body_viewer_regions'], indent=2)};\n"
    )
    return ROOT / "frontend/src/spec/muscleGroups.js", src


def _kotlin_muscle_map(m: dict) -> str:
    primary = ", ".join(_kstr(x) for x in m["primary"])
    secondary = ", ".join(_kstr(x) for x in m["secondary"])
    return f"MuscleMap(primary = listOf({primary}), secondary = listOf({secondary}))"


def gen_muscle_groups_kotlin(spec: dict) -> tuple[Path, str]:
    data = _muscle_groups_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/muscle_groups.yaml")

    cat_muscles = ",\n".join(
        f"    {_kstr(k)} to {_kotlin_muscle_map(v)}"
        for k, v in data["category_muscles"].items()
    )
    muscle_labels = ",\n".join(
        f"    {_kstr(k)} to {_kstr(v)}" for k, v in data["muscle_labels"].items()
    )
    category_labels = ",\n".join(
        f"    {_kstr(k)} to {_kstr(v)}" for k, v in data["category_labels"].items()
    )

    regions = ",\n".join(
        f"    {_kstr(k)} to BodyRegion("
        f"muscle = {_kstr(v['muscle'])}, "
        f"slug = {_kstr(v['slug'])}, "
        f"view = {_kstr(v['view'])})"
        for k, v in data["body_viewer_regions"].items()
    )

    src = (
        banner + "\n\n"
        "package com.tracks.core.spec\n\n"
        f"internal val CATEGORY_MUSCLES: Map<String, MuscleMap> = mapOf(\n{cat_muscles},\n)\n\n"
        f"internal val MUSCLE_LABELS: Map<String, String> = mapOf(\n{muscle_labels},\n)\n\n"
        f"internal val CATEGORY_LABELS: Map<String, String> = mapOf(\n{category_labels},\n)\n\n"
        f"public val BODY_VIEWER_REGIONS: Map<String, BodyRegion> = mapOf(\n{regions},\n)\n"
    )
    return (
        ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/spec/MuscleGroupsData.kt",
        src,
    )


# ── Strength: equipment + experience levels ─────────────────────────────────

def _strength_payload(spec: dict) -> dict:
    return {
        "equipment": spec["equipment"],
        "experience_default_fallback_tier": spec["experience_default_fallback_tier"],
        "experience_levels": spec["experience_levels"],
    }


def _experience_table(levels: list[dict]) -> dict:
    return {
        lvl["value"]: {
            "label": lvl["label"],
            "blurb": lvl["blurb"],
            "default_tier": lvl["default_tier"],
            "max_difficulty": lvl["max_difficulty"],
            "stage_floor": lvl["stage_floor"],
            "starting_weight_factor": lvl["starting_weight_factor"],
        }
        for lvl in levels
    }


def gen_strength_python(spec: dict) -> tuple[Path, str]:
    data = _strength_payload(spec)
    equipment = data["equipment"]
    levels = data["experience_levels"]
    banner = "\n".join(BANNER_LINES).replace(
        "spec/sport_taxonomy.yaml", "spec/strength.yaml")

    valid_equipment = "{" + ", ".join(json.dumps(e["value"]) for e in equipment) + "}"
    experience_levels = "(" + ", ".join(json.dumps(l["value"]) for l in levels) + ")"

    src = (
        '"""\n' + banner + '\n"""\n\n'
        f"EQUIPMENT = {json.dumps(equipment, indent=4)}\n\n"
        f"VALID_EQUIPMENT = {valid_equipment}\n\n"
        f"EXPERIENCE_LEVELS = {experience_levels}\n\n"
        f"EXPERIENCE_TABLE = {_pyliteral(_experience_table(levels))}\n\n"
        f"UNKNOWN_FALLBACK_TIER = {data['experience_default_fallback_tier']}\n"
    )
    return ROOT / "backend/app/spec/strength.py", src


def gen_strength_js(spec: dict) -> tuple[Path, str]:
    data = _strength_payload(spec)
    equipment = data["equipment"]
    levels = data["experience_levels"]
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/strength.yaml")

    src = (
        banner + "\n\n"
        f"export const EQUIPMENT = {json.dumps(equipment, indent=2)};\n\n"
        f"export const VALID_EQUIPMENT = {json.dumps([e['value'] for e in equipment])};\n\n"
        f"export const EXPERIENCE_LEVELS = {json.dumps([l['value'] for l in levels])};\n\n"
        f"export const EXPERIENCE_TABLE = {json.dumps(_experience_table(levels), indent=2)};\n\n"
        f"export const UNKNOWN_FALLBACK_TIER = {data['experience_default_fallback_tier']};\n"
    )
    return ROOT / "frontend/src/spec/strength.js", src


def _kotlin_equipment_option(e: dict) -> str:
    return f"EquipmentOption({_kstr(e['value'])}, {_kstr(e['label'])}, {_kstr(e['description'])})"


def _kotlin_experience_entry(lvl: dict) -> str:
    max_diff = "null" if lvl["max_difficulty"] is None else str(lvl["max_difficulty"])
    return (
        "ExperienceEntry(\n"
        f"        label = {_kstr(lvl['label'])},\n"
        f"        blurb = {_kstr(lvl['blurb'])},\n"
        f"        defaultTierEndurance = {lvl['default_tier']['endurance']},\n"
        f"        defaultTierStrength = {lvl['default_tier']['strength']},\n"
        f"        maxDifficulty = {max_diff},\n"
        f"        stageFloor = {lvl['stage_floor']},\n"
        f"        startingWeightFactor = {lvl['starting_weight_factor']},\n"
        "    )"
    )


def gen_strength_kotlin(spec: dict) -> tuple[Path, str]:
    data = _strength_payload(spec)
    equipment = data["equipment"]
    levels = data["experience_levels"]
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/strength.yaml")

    equipment_list = ",\n".join(f"    {_kotlin_equipment_option(e)}" for e in equipment)
    valid_equipment = ", ".join(_kstr(e["value"]) for e in equipment)
    experience_levels = ", ".join(_kstr(l["value"]) for l in levels)
    table = "\n".join(
        f"    {_kstr(l['value'])} to {_kotlin_experience_entry(l)}," for l in levels
    )

    src = (
        banner + "\n\n"
        "package com.tracks.core.spec\n\n"
        f"internal val EQUIPMENT: List<EquipmentOption> = listOf(\n{equipment_list},\n)\n\n"
        f"internal val VALID_EQUIPMENT: Set<String> = setOf({valid_equipment})\n\n"
        f"internal val EXPERIENCE_LEVELS: List<String> = listOf({experience_levels})\n\n"
        f"internal val EXPERIENCE_TABLE: Map<String, ExperienceEntry> = mapOf(\n{table}\n)\n\n"
        f"internal const val UNKNOWN_FALLBACK_TIER: Int = {data['experience_default_fallback_tier']}\n"
    )
    return (
        ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/spec/StrengthData.kt",
        src,
    )


# ── Fueling ──────────────────────────────────────────────────────────────────

def _fueling_payload(spec: dict) -> dict:
    return {
        "carb_breakpoints": spec["carb_breakpoints"],
        "default_carbs_per_hour": spec["default_carbs_per_hour"],
        "heat_threshold_c": spec["heat_threshold_c"],
        "very_hot_threshold_c": spec["very_hot_threshold_c"],
        "humidity_threshold_pct": spec["humidity_threshold_pct"],
        "humidity_min_temp_c": spec["humidity_min_temp_c"],
        "bands": spec["bands"],
    }


def gen_fueling_python(spec: dict) -> tuple[Path, str]:
    data = _fueling_payload(spec)
    banner = "\n".join(BANNER_LINES).replace(
        "spec/sport_taxonomy.yaml", "spec/fueling.yaml")
    src = (
        '"""\n' + banner + '\n"""\n\n'
        f"CARB_BREAKPOINTS = {json.dumps(data['carb_breakpoints'], indent=4)}\n\n"
        f"DEFAULT_CARBS_PER_HOUR = {data['default_carbs_per_hour']}\n\n"
        f"HEAT_THRESHOLD_C = {data['heat_threshold_c']}\n\n"
        f"VERY_HOT_THRESHOLD_C = {data['very_hot_threshold_c']}\n\n"
        f"HUMIDITY_THRESHOLD_PCT = {data['humidity_threshold_pct']}\n\n"
        f"HUMIDITY_MIN_TEMP_C = {data['humidity_min_temp_c']}\n\n"
        f"BANDS = {json.dumps(data['bands'], indent=4)}\n"
    )
    return ROOT / "backend/app/spec/fueling.py", src


def gen_fueling_js(spec: dict) -> tuple[Path, str]:
    data = _fueling_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/fueling.yaml")
    src = (
        banner + "\n\n"
        f"export const CARB_BREAKPOINTS = {json.dumps(data['carb_breakpoints'], indent=2)};\n\n"
        f"export const DEFAULT_CARBS_PER_HOUR = {data['default_carbs_per_hour']};\n\n"
        f"export const HEAT_THRESHOLD_C = {data['heat_threshold_c']};\n\n"
        f"export const VERY_HOT_THRESHOLD_C = {data['very_hot_threshold_c']};\n\n"
        f"export const HUMIDITY_THRESHOLD_PCT = {data['humidity_threshold_pct']};\n\n"
        f"export const HUMIDITY_MIN_TEMP_C = {data['humidity_min_temp_c']};\n\n"
        f"export const BANDS = {json.dumps(data['bands'], indent=2)};\n"
    )
    return ROOT / "frontend/src/spec/fueling.js", src


def _kotlin_carb_breakpoint(b: dict) -> str:
    return f"CarbBreakpoint({b['max_hours']}, {b['carbs_per_hour']})"


def _kotlin_fueling_band(b: dict) -> str:
    return f"FuelingBand({b['concentration_pct']}, {b['sip_interval_min']}, {b['salt_index']})"


def gen_fueling_kotlin(spec: dict) -> tuple[Path, str]:
    data = _fueling_payload(spec)
    banner = _banner("//").replace("spec/sport_taxonomy.yaml", "spec/fueling.yaml")

    breakpoints = ",\n".join(
        f"    {_kotlin_carb_breakpoint(b)}" for b in data["carb_breakpoints"]
    )
    bands = "\n".join(
        f"    {_kstr(k)} to {_kotlin_fueling_band(v)}," for k, v in data["bands"].items()
    )

    src = (
        banner + "\n\n"
        "package com.tracks.core.spec\n\n"
        f"internal val CARB_BREAKPOINTS: List<CarbBreakpoint> = listOf(\n{breakpoints},\n)\n\n"
        f"internal const val DEFAULT_CARBS_PER_HOUR: Int = {data['default_carbs_per_hour']}\n\n"
        f"internal const val HEAT_THRESHOLD_C: Int = {data['heat_threshold_c']}\n\n"
        f"internal const val VERY_HOT_THRESHOLD_C: Int = {data['very_hot_threshold_c']}\n\n"
        f"internal const val HUMIDITY_THRESHOLD_PCT: Int = {data['humidity_threshold_pct']}\n\n"
        f"internal const val HUMIDITY_MIN_TEMP_C: Int = {data['humidity_min_temp_c']}\n\n"
        f"internal val BANDS: Map<String, FuelingBand> = mapOf(\n{bands}\n)\n"
    )
    return (
        ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/spec/FuelingData.kt",
        src,
    )


# ── Sync registry ────────────────────────────────────────────────────────────

def _sync_banner(comment: str) -> str:
    # The shared banner names sport_taxonomy.yaml as its source; this file is
    # generated from sync.yaml, and someone chasing a wrong field list needs to
    # be sent to the right place.
    return _banner(comment).replace("spec/sport_taxonomy.yaml", "spec/sync.yaml")


def _kotlin_str_list(values: list) -> str:
    return "listOf(" + ", ".join(_kstr(v) for v in values) + ")"


def gen_sync_kotlin(spec: dict) -> tuple[Path, str]:
    """The entity registry the phone's merge reads.

    Only the executable facts: kind, fields, references, uid templates and
    parent links. The merge rules themselves are hand-written in
    com.tracks.core.replica.Merge and held to the server's by
    spec/fixtures/sync_scenarios.json, like every other evaluator here.
    """
    kinds = {"source": "SOURCE", "log": "LOG", "readonly": "READONLY"}
    entities = []
    for name, e in spec["entities"].items():
        refs = e.get("refs") or {}
        refs_src = "mapOf(" + ", ".join(
            f"{_kstr(k)} to {_kstr(v)}" for k, v in refs.items()
        ) + ")"
        child = e.get("children_of")
        child_src = (
            f"ChildOf(field = {_kstr(child['field'])}, entity = {_kstr(child['entity'])})"
            if child else "null"
        )
        key = _kstr(e["uid_key"]) if e.get("uid_key") else "null"
        fallback = _kstr(e["uid_key_fallback"]) if e.get("uid_key_fallback") else "null"
        entities.append(
            "    EntitySpec(\n"
            f"        name = {_kstr(name)},\n"
            f"        kind = EntityKind.{kinds[e['kind']]},\n"
            f"        fields = {_kotlin_str_list(e['fields'])},\n"
            f"        refs = {refs_src},\n"
            f"        uidKey = {key},\n"
            f"        uidKeyFallback = {fallback},\n"
            f"        childOf = {child_src},\n"
            "    ),"
        )
    src = (
        _sync_banner("//") + "\n\n"
        "package com.tracks.core.replica\n\n"
        f"internal const val SYNC_SPEC_VERSION: Int = {int(spec['version'])}\n\n"
        f"internal const val UID_NAMESPACE: String = {_kstr(spec['uid_namespace'])}\n\n"
        f"internal const val HLC_MAX_SKEW_MS: Long = {int(spec['hlc']['max_skew_ms'])}L\n\n"
        f"internal const val PULL_DEFAULT_LIMIT: Int = {int(spec['wire']['pull_default_limit'])}\n\n"
        f"internal const val PULL_MAX_LIMIT: Int = {int(spec['wire']['pull_max_limit'])}\n\n"
        "internal val ENTITY_SPECS: List<EntitySpec> = listOf(\n"
        + "\n".join(entities)
        + "\n)\n"
    )
    return (
        ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/replica/SyncRegistryData.kt",
        src,
    )


# The backend's copy. It has no YAML dependency at runtime and the production
# image does not carry spec/, so the registry reaches it the way every other
# table does — generated into app/spec.

def gen_sync_python(spec: dict) -> tuple[Path, str]:
    banner = "\n".join(BANNER_LINES).replace(
        "spec/sport_taxonomy.yaml", "spec/sync.yaml")
    entities = {}
    for name, e in spec["entities"].items():
        entities[name] = {
            "kind": e["kind"],
            "table": e["table"],
            "uid_key": e.get("uid_key"),
            "uid_key_fallback": e.get("uid_key_fallback"),
            "fields": list(e["fields"]),
            "refs": dict(e.get("refs") or {}),
            "children_of": e.get("children_of"),
        }
    src = (
        '"""\n' + banner + '\n"""\n\n'
        f"VERSION = {spec['version']}\n\n"
        f"HLC_MAX_SKEW_MS = {spec['hlc']['max_skew_ms']}\n\n"
        f"UID_NAMESPACE = {json.dumps(spec['uid_namespace'])}\n\n"
        f"DELETE_WINS = {bool(spec['merge']['delete_wins'])}\n\n"
        f"PULL_DEFAULT_LIMIT = {spec['wire']['pull_default_limit']}\n\n"
        f"PULL_MAX_LIMIT = {spec['wire']['pull_max_limit']}\n\n"
        f"ENTITIES = {_pyliteral(entities)}\n"
    )
    return ROOT / "backend/app/spec/sync.py", src


# ── Design tokens ────────────────────────────────────────────────────────────

def _design_banner(comment: str) -> str:
    return _banner(comment).replace("spec/sport_taxonomy.yaml", "spec/design.yaml")


def _rem(px) -> str:
    # Tailwind's own scale is in rem, so the generated one is too: a browser
    # with a larger default font scales these exactly as it scaled the originals.
    if px == 0:
        return "0px"
    if px >= 9999:
        return "9999px"
    return f"{px / 16:g}rem"


def gen_design_js(spec: dict) -> tuple[Path, str]:
    """The Tailwind theme extension. `extend`, never a replacement: the spec
    names the steps Tracks designs with, and replacing Tailwind's scale would
    delete every class (w-64, h-96) the layout uses that the spec does not name."""
    font = [spec["font"]["family"], *spec["font"]["fallback"]]
    radius = {k: _rem(v) for k, v in spec["radius"].items()}
    spacing = {k: _rem(v) for k, v in spec["spacing"].items()}
    font_size = {k: [_rem(s), {"lineHeight": _rem(lh)}] for k, (s, lh) in spec["type"].items()}
    tracking = {k: f"{v:g}em" for k, v in spec["tracking"].items()}
    weight = {k: str(v) for k, v in spec["weight"].items()}
    body = {
        "fontFamily": {"sans": font},
        "borderRadius": radius,
        "spacing": spacing,
        "fontSize": font_size,
        "letterSpacing": tracking,
        "fontWeight": weight,
    }
    lines = [
        _design_banner("//"),
        "",
        "/** Tailwind `theme.extend`, from spec/design.yaml. */",
        f"export const designTheme = {json.dumps(body, indent=2, ensure_ascii=False)};",
        "",
        "/** Component specs, for code that styles outside Tailwind (charts, canvases). */",
        f"export const designComponents = {json.dumps(spec['components'], indent=2)};",
        "",
    ]
    return ROOT / "frontend/src/design/tokens.js", "\n".join(lines)


def _kname(key: str, prefix: str) -> str:
    """A Kotlin identifier for a scale step: "2xl" → xl2, "3.5" → s3_5, DEFAULT → base."""
    if key == "DEFAULT":
        return "base"
    if key[0].isdigit() and not key.replace(".", "").isdigit():
        n, rest = key[0], key[1:]
        return f"{rest}{n}"
    return f"{prefix}{key.replace('.', '_')}" if key[0].isdigit() else key


def gen_design_kotlin(spec: dict) -> tuple[Path, str]:
    r, sp, ty = spec["radius"], spec["spacing"], spec["type"]
    wt, tr, el = spec["weight"], spec["tracking"], spec["elevation"]
    comp = spec["components"]
    k = lambda key, pre="": _kname(key, pre)

    def text_style(c: dict) -> str:
        size, lh = ty[c["type"]]
        parts = [
            "fontFamily = InterFamily",
            f"fontSize = {size}.sp",
            f"lineHeight = {lh}.sp",
            f"fontWeight = FontWeight({wt[c.get('weight', 'normal')]})",
        ]
        if "tracking" in c:
            parts.append(f"letterSpacing = ({tr[c['tracking']]:g}).em")
        if c.get("tabular"):
            parts.append('fontFeatureSettings = "tnum"')
        return "TextStyle(" + ", ".join(parts) + ")"

    out = [
        _design_banner("//"),
        "package com.tracks.app.ui.theme",
        "",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.FontWeight",
        "import androidx.compose.ui.unit.dp",
        "import androidx.compose.ui.unit.em",
        "import androidx.compose.ui.unit.sp",
        "",
        "/** The fixed design layer, from spec/design.yaml — the same steps the web's Tailwind theme uses. */",
        "object Tokens {",
        "    object Radius {",
        *[f"        val {k(n)} = {min(v, 999)}.dp" for n, v in r.items()],
        "    }",
        "",
        "    /** Tailwind's spacing steps: `s3_5` is `p-3.5`, 14dp. */",
        "    object Space {",
        *[f"        val {k(n, 's')} = {v}.dp" for n, v in sp.items()],
        "    }",
        "",
        "    /** Font size and line height of each step of the type scale. */",
        "    object Type {",
        *[f"        val {k(n)} = TypeStep({s}.sp, {lh}.sp)" for n, (s, lh) in ty.items()],
        "    }",
        "",
        "    object Weight {",
        *[f"        val {n} = FontWeight({v})" for n, v in wt.items()],
        "    }",
        "",
        "    object Tracking {",
        *[f"        val {n} = ({v:g}).em" for n, v in tr.items()],
        "    }",
        "",
        "    object Elevation {",
        *[f"        val {n} = {v}.dp" for n, v in el.items()],
        "    }",
        "",
        "    object Card {",
        f"        val radius = Radius.{k(comp['card']['radius'])}",
        f"        val padding = Space.{k(comp['card']['padding'], 's')}",
        f"        val border = {comp['card']['border']}.dp",
        "    }",
        "",
        "    object SectionHeader {",
        f"        val style = {text_style(comp['section_header'])}",
        f"        const val uppercase = {str(comp['section_header'].get('uppercase', False)).lower()}",
        "    }",
        "",
        "    object Stat {",
        f"        val value = {text_style(comp['stat_value'])}",
        f"        val label = {text_style(comp['stat_label'])}",
        "    }",
        "",
    ]
    for name, key in (("Chip", "chip"), ("Pill", "pill"), ("Button", "button")):
        c = comp[key]
        out += [
            f"    object {name} {{",
            f"        val style = {text_style(c)}",
            f"        val radius = Radius.{k(c['radius'])}",
            f"        val paddingX = Space.{k(c['padding_x'], 's')}",
            f"        val paddingY = Space.{k(c['padding_y'], 's')}",
            *[f"        val {camel} = Space.{k(c[key2], 's')}"
              for key2, camel in (("height", "height"), ("height_sm", "heightSm"), ("padding_x_sm", "paddingXSm"))
              if key2 in c],
            *[f"        const val {camel} = {c[key2]}f"
              for key2, camel in (("tonal_alpha", "tonalAlpha"), ("neutral_alpha", "neutralAlpha"))
              if key2 in c],
            "    }",
            "",
        ]
    out[-1:] = ["}", ""]
    return ROOT / "mobile/app/src/main/java/com/tracks/app/ui/theme/TokensData.kt", "\n".join(out)


GENERATORS = {
    "sport_taxonomy": [
        gen_sport_taxonomy_python,
        gen_sport_taxonomy_js,
        gen_sport_taxonomy_kotlin,
    ],
    "zones": [
        gen_zones_python,
        gen_zones_js,
        gen_zones_kotlin,
    ],
    "muscle_groups": [
        gen_muscle_groups_python,
        gen_muscle_groups_js,
        gen_muscle_groups_kotlin,
    ],
    "strength": [
        gen_strength_python,
        gen_strength_js,
        gen_strength_kotlin,
    ],
    "fueling": [
        gen_fueling_python,
        gen_fueling_js,
        gen_fueling_kotlin,
    ],
    "sync": [
        gen_sync_kotlin,
        gen_sync_python,
    ],
    "design": [
        gen_design_js,
        gen_design_kotlin,
    ],
}


# Generators that live in their own scripts because their source is backend
# data rather than a spec/ yaml, but whose output must not go stale any more
# than the rest. make_fit_profile.py is not here: it needs fitdecode, which
# only the backend image has.
DATA_SCRIPTS = ("make_coaching_data.py", "make_archetype_data.py", "make_library_data.py", "make_animation_data.py")


def _data_script_outputs():
    import importlib.util
    for name in DATA_SCRIPTS:
        spec = importlib.util.spec_from_file_location(name[:-3], ROOT / "spec" / name)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        out = mod.render()
        # One script may emit several files (the library feeds phone and server).
        yield from (out if isinstance(out, list) else [out])


def main() -> int:
    check_only = "--check" in sys.argv
    stale, written = [], []

    outputs = [(gen, name) for name, gens in GENERATORS.items() for gen in gens]
    specs = {name: load_spec(name) for name in GENERATORS}
    results = [gen(specs[name]) for gen, name in outputs] + list(_data_script_outputs())
    for path, src in results:
        existing = path.read_text() if path.exists() else None
        if existing == src:
            continue
        if check_only:
            stale.append(path.relative_to(ROOT))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(src)
        written.append(path.relative_to(ROOT))

    if check_only:
        if stale:
            print("codegen: out of date — run `python3 spec/codegen.py`:")
            for p in stale:
                print(f"  {p}")
            return 1
        print("codegen: all generated files up to date")
        return 0

    if written:
        for p in written:
            print(f"codegen: wrote {p}")
    else:
        print("codegen: nothing to do")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
