# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Compile the exercise and stretch libraries for the phone and the server.

spec/library/{exercises,stretches}.json IS the library. It ships inside both
apps: a phone that never sees a server needs the same exercises, the same
Garmin mappings and the same muscles, and a library that could differ between
the two would make the same plan mean different things on each. The server's
`exercise_library`/`stretch_library` tables are loaded from it at startup
(app.seed) and exist only so its queries can filter and search in SQL.

To change an exercise, edit the JSON and run `python3 spec/codegen.py`; that
regenerates both outputs, and `--check` fails if either is stale.

Each entry is its own string literal in the Kotlin because a JVM class caps any
one constant at 64 KB, and the libraries together are several times that.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "spec" / "library"
OUT = (ROOT / "mobile" / "core" / "src" / "commonMain" / "kotlin" / "com" / "tracks" / "core"
       / "spec" / "LibraryData.kt")
PY_OUT = ROOT / "backend" / "app" / "spec" / "library.py"


def _kotlin_string(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "$":
            out.append("\\$")
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) < 0x20:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _rows(name: str) -> list[dict]:
    return json.loads((SRC / f"{name}.json").read_text())


def _entries(name: str) -> list[str]:
    return [json.dumps(r, sort_keys=True, ensure_ascii=False, separators=(",", ":")) for r in _rows(name)]


def _python() -> str:
    # The backend image does not carry spec/, so the library reaches it as a
    # generated module, like every other spec table.
    return "\n".join([
        '"""',
        "SPDX-FileCopyrightText: 2026 Hawk Fugagli",
        "SPDX-License-Identifier: AGPL-3.0-or-later",
        "",
        "GENERATED FILE — DO NOT EDIT.",
        "",
        "Source: spec/library/*.json",
        "Regenerate: python3 spec/codegen.py",
        '"""',
        "import json",
        "",
        f"EXERCISES: list[dict] = json.loads({json.dumps(json.dumps(_rows('exercises'), ensure_ascii=False, sort_keys=True), ensure_ascii=False)})",
        f"STRETCHES: list[dict] = json.loads({json.dumps(json.dumps(_rows('stretches'), ensure_ascii=False, sort_keys=True), ensure_ascii=False)})",
        "",
    ])


def render() -> list[tuple[Path, str]]:
    """Both generated files and their text, without writing — codegen.py uses this."""
    ex = _entries("exercises")
    st = _entries("stretches")
    lines = [
        "// SPDX-FileCopyrightText: 2026 Hawk Fugagli",
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "//",
        "// GENERATED by spec/make_library_data.py from spec/library/*.json.",
        "// Do not edit — change the JSON and rerun the script.",
        "package com.tracks.core.spec",
        "",
        "/** One JSON object per exercise, as the server's `exercise_library` holds it. */",
        "internal val EXERCISE_LIBRARY_JSON: List<String> = listOf(",
        *[f"    {_kotlin_string(e)}," for e in ex],
        ")",
        "",
        "/** One JSON object per stretch, as the server's `stretch_library` holds it. */",
        "internal val STRETCH_LIBRARY_JSON: List<String> = listOf(",
        *[f"    {_kotlin_string(s)}," for s in st],
        ")",
        "",
    ]
    return [(OUT, "\n".join(lines)), (PY_OUT, _python())]


def main() -> None:
    for path, text in render():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
