# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Compile the coaching paragraph library into the phone's core module.

The server loads backend/app/data/coaching_paragraphs/*.json at import; the
phone has no such directory, and the words a coach says have to be the same
words on both. So the files are embedded verbatim, in the order the server
reads them (sorted by name), and com.tracks.core.coaching merges them the same
way.

Rerun after editing any paragraph file:

    python3 spec/make_coaching_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "backend/app/data/coaching_paragraphs"
OUT = ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/coaching/CoachingParagraphsData.kt"


def _kotlin_string(text: str) -> str:
    # A plain string literal with every escape spelled out: raw strings would
    # interpolate `$`, and a stray `"""` would end one.
    return json.dumps(text, ensure_ascii=False).replace("$", "\\$")


def render() -> tuple[Path, str]:
    """The generated file and its text, without writing it — codegen.py --check uses this."""
    lines = [
        "// SPDX-FileCopyrightText: 2026 Hawk Fugagli",
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "//",
        "// GENERATED by spec/make_coaching_data.py from backend/app/data/coaching_paragraphs/.",
        "// Do not edit — change the JSON and rerun the script.",
        "package com.tracks.core.coaching",
        "",
        "internal val COACHING_PARAGRAPH_FILES: List<Pair<String, String>> = listOf(",
    ]
    for path in sorted(SRC.glob("*.json")):
        lines.append(f"    {_kotlin_string(path.name)} to {_kotlin_string(path.read_text())},")
    lines.append(")")
    lines.append("")
    return OUT, "\n".join(lines)


def main() -> None:
    out, text = render()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
