# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Baseline the race-predictor corpus: calculators/race_predictor/, in-process.

com.tracks.core.race.RacePredictor replays every case. Courses are synthetic
segment lists and path points (no GPX parsing — the phone port does not do
that) and nothing is personal.

    docker run --rm --env-file .env -v "$PWD/backend:/app" -v "$PWD/spec:/spec" \\
        tracks-backend python /spec/make_race_predictor_fixtures.py
"""
from __future__ import annotations

import json
import math
import random
import sys
from pathlib import Path

sys.path.insert(0, "/app")

from app.calculators import race_predictor as rp  # noqa: E402
from app.calculators.race_predictor.formatting import _fmt_pace  # noqa: E402

OUT = Path("/spec/fixtures/race_predictor.json")


def _segments(seed: int, n: int, amp: float) -> list[dict]:
    rnd = random.Random(seed)
    out = []
    for i in range(n):
        d = round(90 + rnd.random() * 30, 1)
        g = round(amp * math.sin(i / 3.0) + rnd.uniform(-amp, amp) / 2, 4)
        out.append({"distance_m": d, "elevation_gain_m": round(g * d, 1), "gradient": g})
    return out


def _path(seed: int, n: int) -> list[list]:
    rnd = random.Random(seed)
    lat, lon = 39.75, -150.22
    pts = [[lat, lon, None]]
    heading = rnd.uniform(0, 2 * math.pi)
    for _ in range(n):
        heading += rnd.uniform(-0.6, 0.6)
        lat += math.cos(heading) * 0.0009
        lon += math.sin(heading) * 0.0011
        pts.append([round(lat, 6), round(lon, 6), None])
    pts.append(list(pts[-1]))   # a zero-length step must be skipped
    return pts


COURSES = {
    "none": None,
    "flat": [{"distance_m": 100.0, "elevation_gain_m": 0.0, "gradient": 0.0}] * 50,
    "rolling": _segments(1, 120, 0.04),
    "hilly": _segments(2, 220, 0.09),
    "steep": _segments(3, 60, 0.25),
}


def _laps(laps):
    return [dict(l) for l in laps]


def main() -> None:
    fx: dict = {"_comment": "Generated by spec/make_race_predictor_fixtures.py. Do not edit."}
    fx["courses"] = {k: v for k, v in COURSES.items() if v is not None}
    fx["format_time"] = [{"s": s, "expected": rp.format_time(s)}
                         for s in (0.0, 59.5, 60.5, 599.49, 3599.5, 3600.0, 3661.2, 12345.5, 86399.9)]
    fx["fmt_pace"] = [{"s": s, "expected": _fmt_pace(s)}
                      for s in (0.0, 59.999, 60.0, 239.99999999999997, 359.99999999999994, 305.7, 1234.5)]
    fx["swim_pace"] = [{"css": c, "i": i, "expected": rp.format_swim_pace(c, i)}
                       for c in (85.0, 99.9, 120.0) for i in (0.88, 1.0, 1.06)]
    fx["grade"] = [{"g": g, "mult": rp.grade_cost_multiplier(g), "gap": rp.grade_adjustment_factor(g)}
                   for g in (-0.6, -0.45, -0.3, -0.2, -0.15, -0.10, -0.05, -0.01, 0.0, 0.01, 0.05, 0.1, 0.2, 0.45, 0.6)]
    fx["weather"] = [{"t": t, "h": h, "w": w, "a": a, "expected": rp.weather_slowdown_factor(t, h, w, a)}
                     for t in (-5.0, 10.0, 22.5, 35.0) for h in (0.0, 55.0, 100.0)
                     for w, a in ((0.0, 0.0), (4.0, 0.0), (4.0, 90.0), (6.5, 180.0), (3.0, -45.0), (5.0, 720.0))]
    paths = {"loop": _path(7, 80), "line": _path(8, 40), "short": [[39.0, -150.0, None], [39.0, -150.0, None]]}
    fx["paths"] = paths
    fx["wind"] = [{"path": p, "dir": d, "mps": m,
                   "run": rp.compute_wind_course_exposure(paths[p], d, m),
                   "bike": rp.compute_cycling_wind_course_exposure(paths[p], d, m)}
                  for p in paths for d in (0.0, 135.0, 270.0) for m in (0.0, 3.0, 8.0)]
    fx["course"] = [{"course": k, "tech": list(rp.compute_technicality_factor(v)), "totals": rp.course_totals(v)}
                    for k, v in COURSES.items() if v is not None]
    fx["course"].append({"course": None, "tech": list(rp.compute_technicality_factor([])), "totals": rp.course_totals([])})
    fx["run_predict"] = [{"vdot": v, "d": d, "expected": rp.predict_race_time_sec(v, d)}
                         for v in (30.0, 45.5, 62.0) for d in (1609.34, 5000.0, 21097.5, 42195.0)]
    # The marathon's training-volume correction (Tanda 2011, blended).
    from datetime import date as _date, timedelta as _td
    from random import Random
    from app.calculators.race_predictor.running import tanda_marathon_sec
    fx["run_volume"] = [
        {"vdot": v, "d": d, "k": k, "p": p, "f": f,
         "expected": rp.predict_running_race_sec(v, d, None if k is None else (k, p), f)}
        for v in (30.0, 45.5, 62.0) for d in (21097.5, 40000.0, 42195.0, 44000.0, 44001.0, 50000.0)
        for k, p in ((None, None), (25.0, 390.0), (60.0, 330.0), (120.0, 280.5)) for f in (1.0, 0.97)
    ]
    fx["tanda"] = [{"k": k, "p": p, "d": d, "expected": tanda_marathon_sec(k, p, d)}
                   for k in (0.0, 20.0, 57.3, 150.0) for p in (240.0, 333.3, 480.0) for d in (42195.0, 41000.0)]
    today = _date(2026, 3, 4)
    rng = Random("training-indices")
    idx_cases = []
    for i in range(30):
        runs = [{"date": (today - _td(days=rng.randint(-5, 70))).isoformat(),
                 "distance_m": rng.choice([None, 0.0, round(rng.uniform(2000, 30000), 1)]),
                 "duration_s": rng.choice([None, round(rng.uniform(600, 10000), 1)])}
                for _ in range(rng.randint(0, 20))]
        parsed = [{**r, "date": _date.fromisoformat(r["date"])} for r in runs]
        got = rp.training_indices(parsed, today)
        idx_cases.append({"today": today.isoformat(), "runs": runs,
                          "expected": None if got is None else list(got)})
    fx["training_indices"] = idx_cases
    fx["hr"] = [{"max_hr": h, "d": d, "n": n, "run": rp.compute_hr_ceilings(h, d, n),
                 "bike": rp.compute_cycling_hr_ceilings(h, d, n)}
                for h in (180, 195) for d in (1500.0, 5000.0, 10000.0, 21097.0, 42195.0, 60000.0, 100000.0, 200000.0)
                for n in (1, 2, 7)]
    # With the split ramp: a negative split caps HR lower early, higher late.
    from app.calculators.race_predictor.running import _split_ramp
    fx["hr_split"] = [{"max_hr": h, "d": d, "n": n, "spread": sp, "ramp": _split_ramp(n, sp),
                       "run": rp.compute_hr_ceilings(h, d, n, _split_ramp(n, sp)),
                       "bike": rp.compute_cycling_hr_ceilings(h, d, n, _split_ramp(n, sp))}
                      for h in (180, 195) for d in (5000.0, 21097.0, 100000.0)
                      for n in (2, 7) for sp in (-1.0, -0.3, 0.5, 1.0)]
    fx["run_laps"] = []
    for course in ("none", "flat", "hilly"):
        for spread in (-1.0, 0.0, 0.5):
            for d, pred, lap_km, hr in ((5000.0, 1500.0, 1.0, 190), (10005.0, 3000.0, 1.0, None), (21097.5, 6600.0, 5.0, 185)):
                laps, total = rp.compute_lap_paces(pred, d, spread, lap_km, COURSES[course], hr)
                fx["run_laps"].append({"course": course, "spread": spread, "d": d, "pred": pred, "lap_km": lap_km,
                                       "hr": hr, "laps": _laps(laps), "total": total})
    # Terrain splits (race_predictor/terrain.py): the course cut by its ground.
    # "wall" is the case they exist for — a short steep hill in a flat course.
    wall = ([{"distance_m": 100.0, "elevation_gain_m": 0.0, "gradient": 0.0}] * 20
            + [{"distance_m": 100.0, "elevation_gain_m": 9.0, "gradient": 0.09}] * 3
            + [{"distance_m": 100.0, "elevation_gain_m": 0.0, "gradient": 0.0}] * 27)
    fx["courses"]["wall"] = wall
    terrain_courses = {**COURSES, "wall": wall}
    fx["terrain_laps"] = []
    for course in ("wall", "rolling", "hilly", "steep"):
        for spread in (-1.0, 0.0, 0.5):
            for d, pred, hr in ((5000.0, 1500.0, 190), (21097.5, 6600.0, None), (42195.0, 13000.0, 185)):
                laps, total = rp.compute_lap_paces(pred, d, spread, 1.0, terrain_courses[course], hr, terrain=True)
                fx["terrain_laps"].append({"course": course, "spread": spread, "d": d, "pred": pred,
                                           "hr": hr, "laps": _laps(laps), "total": total})
    fx["bike_predict"] = [{"ftp": f, "d": d, "course": c, "wind": w,
                           "expected": rp.predict_cycling_time_sec(f, d, COURSES[c], w)}
                          for f in (150.0, 260.0) for d in (20000.0, 90000.0)
                          for c in ("none", "rolling", "steep") for w in (0.0, 3.0, -2.0)]
    fx["bike_laps"] = []
    for course in ("none", "rolling", "hilly"):
        for d, ftp, lap_km, hr, pred, wind, spread in (
            (40000.0, 250.0, 5.0, 185, None, 0.0, 0.0),
            (20005.0, 180.0, 1.0, None, 2400.0, 2.5, 0.8),
            (100000.0, 300.0, 10.0, 190, None, -1.5, -0.5),
        ):
            laps, total = rp.compute_cycling_lap_targets(ftp, d, spread, lap_km, COURSES[course], hr, pred, wind)
            fx["bike_laps"].append({"course": course, "d": d, "ftp": ftp, "lap_km": lap_km, "hr": hr,
                                    "pred": pred, "wind": wind, "spread": spread, "laps": _laps(laps), "total": total})
    fx["swim"] = [{"css": c, "d": d, "ow": ow, "expected": rp.predict_swim_time_sec(c, d, ow)}
                  for c in (85.0, 110.5) for d in (100.0, 400.0, 750.0, 1500.0, 1900.0, 3800.0, 5000.0)
                  for ow in (False, True)]
    OUT.write_text(json.dumps(fx, indent=1) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
