# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Compile Garmin's animation manifest into the phone's core module.

The server reads backend/app/data/garmin_animations.json to decide which
exercises animate on a watch — the gate every generated stretch flow passes
through (a stretch that does not animate in the watch's Yoga app is dropped).
A phone that plans on its own needs the same gate or its flows differ from the
server's. Only what the gate reads is kept: each (category, name) pair and
whether the Yoga app renders it as a pose, move or plank.

Rerun after the manifest changes (codegen.py --check notices if you do not):

    python3 spec/make_animation_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "backend/app/data/garmin_animations.json"
OUT = ROOT / "mobile/core/src/commonMain/kotlin/com/tracks/core/strengthplan/GarminAnimationsData.kt"

_YOGA_CATEGORIES = {"pose", "move", "plank"}


def render() -> tuple[Path, str]:
    """The generated file and its text, without writing it — codegen.py --check uses this."""
    rows = json.loads(SRC.read_text())
    pairs = sorted({(int(r["cat_int"]), int(r["name_int"])) for r in rows})
    yoga = sorted({
        (int(r["cat_int"]), int(r["name_int"])) for r in rows
        if "Yoga" in r["in"] and r["cat"] in _YOGA_CATEGORIES
    })

    def encode(ps):
        # One string of "cat:name" pairs rather than a listOf() of 1700
        # entries: a large collection literal is one huge JVM method, which
        # hits the 64 KB method limit long before the data runs out.
        return ",".join(f"{c}:{n}" for c, n in ps)

    lines = [
        "// SPDX-FileCopyrightText: 2026 Hawk Fugagli",
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "//",
        "// GENERATED by spec/make_animation_data.py from backend/app/data/garmin_animations.json.",
        "// Do not edit — change the JSON and rerun the script.",
        "package com.tracks.core.strengthplan",
        "",
        "/** Every (exercise_category, exercise_name) pair Garmin Connect animates, as `cat:name,…`. */",
        f'internal const val ANIMATED_PAIRS: String = "{encode(pairs)}"',
        "",
        "/** The subset the watch's Yoga app renders (pose, move or plank categories). */",
        f'internal const val YOGA_ANIMATED_PAIRS: String = "{encode(yoga)}"',
        "",
    ]
    return OUT, "\n".join(lines)


def main() -> None:
    out, text = render()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
