# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Baseline the matching corpus: what a matched activity updates.

Runs field_test_updates, strength_fingerprint_updates and
activity_local_date from
api/training_plan/matching.py in-process; com.tracks.core.plan.Matching
replays every case. Synthetic inputs, no database.

    docker run --rm --env-file .env -v "$PWD/backend:/app" -v "$PWD/spec:/spec" \\
        tracks-backend python /spec/make_matching_fixtures.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, "/app")

from datetime import datetime  # noqa: E402

from app.api.training_plan.matching import (  # noqa: E402
    activity_local_date, field_test_updates, strength_fingerprint_updates,
)

OUT = Path("/spec/fixtures/matching.json")


def main() -> None:
    field = []
    for test in ("ftp20", "pmax5", "rsa"):
        for watts in (None, 0.0, 83.0, 84.3, 250.0, 631.0, 632.0, 263.1578947368421):
            for hr in (None, 0, 117, 118, 185, 209, 210):
                for fm, hm in (("auto", "auto"), ("manual", "auto"), ("auto", "manual"), (None, None)):
                    field.append({"test": test, "watts": watts, "max_hr": hr, "ftp_mode": fm, "hr_mode": hm,
                                  "expected": field_test_updates(test, watts, hr, fm, hm)})

    def s(name, w, r):
        return {"exercise_name": name, "weight_kg": w, "repetitions": r}

    strength = []
    for sets, existing in [
        ([], {}),
        ([s(None, 50.0, 5), s("", 50.0, 5)], {}),
        ([s("Squat", 100.0, 5), s("Squat", 102.5, 5), s("Squat", 105.0, 3)], {}),
        ([s("Squat", 100.0, 12), s("Squat", 60.0, 1)], {"Squat": {"estimated_1rm_kg": 140.0, "sessions_completed": 19}}),
        ([s("Bench", 80.0, 8), s("Row", 70.0, 10), s("Bench", 82.5, 6)],
         {"Bench": {"estimated_1rm_kg": 90.0, "sessions_completed": 99}, "Row": {"estimated_1rm_kg": None, "sessions_completed": None}}),
        ([s("Curl", 12.5, 10), s("Curl", 12.5, 10), s("Curl", 0.1, 3)], {"Curl": {"estimated_1rm_kg": 16.6, "sessions_completed": 4}}),
        ([s("Dip", 0.0, 8), s("Dip", 22.5, 0)], {}),
    ]:
        strength.append({"sets": sets, "existing": existing,
                         "expected": strength_fingerprint_updates(sets, existing)})

    # Stored start times, in the two shapes the phone holds them in, across
    # the evening boundary, a DST change, zones either side of UTC and the
    # date line, and zones that fall back to UTC.
    local_dates = []
    for started in ("2026-10-01 01:04:12+00:00", "2026-10-01T06:59:59+00:00", "2026-10-01 07:00:00+00:00",
                    "2026-11-01 07:30:00+00:00", "2026-11-01 08:30:00+00:00", "2026-03-08 09:59:00+00:00",
                    "2026-12-31 23:30:00+00:00", "2026-06-15 11:00:00.250000+00:00", "2026-09-25T07:00:00"):
        for tz in ("America/Los_Angeles", "America/Edmonton", "Europe/Berlin", "Asia/Kolkata",
                   "Pacific/Kiritimati", "Pacific/Pago_Pago", "UTC", None, "", "Not/AZone"):
            at = datetime.fromisoformat(started)
            local_dates.append({"started_at": started, "tz": tz,
                                "expected": activity_local_date(at, tz).isoformat()})

    OUT.write_text(json.dumps({
        "_comment": "Generated by spec/make_matching_fixtures.py from matching.py. Do not edit.",
        "field_tests": field,
        "strength": strength,
        "local_dates": local_dates,
    }, indent=1) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
