# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Compile the workout archetypes into the phone's core module.

The server reads backend/app/data/archetypes/{strength,flows}/*.json at import
time. The phone has no such directory, and reading assets is a platform API
that common code may not touch — so the same files are embedded, verbatim and
in the same (filename) order, into ArchetypeData.kt. Verbatim rather than
translated so that the Kotlin parser in com.tracks.core.strengthplan applies
the server's validation to exactly the text the server validates.

Run from the repository root after changing an archetype:

    python3 spec/make_archetype_data.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "backend" / "app" / "data" / "archetypes"
OUT = (ROOT / "mobile" / "core" / "src" / "commonMain" / "kotlin" / "com" / "tracks" / "core"
       / "strengthplan" / "ArchetypeData.kt")


def _kotlin_string(text: str) -> str:
    # A plain string literal with every escape spelled out: raw strings would
    # interpolate `$`, and a stray `"""` would end one.
    return json.dumps(text, ensure_ascii=False).replace("$", "\\$")


def _files(kind: str) -> list[tuple[str, str]]:
    return [(p.name, p.read_text()) for p in sorted((SRC / kind).glob("*.json"), key=lambda p: p.name)]


def render() -> tuple[Path, str]:
    """The generated file and its text, without writing it — codegen.py --check uses this."""
    lines = [
        "// SPDX-FileCopyrightText: 2026 Hawk Fugagli",
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "//",
        "// GENERATED by spec/make_archetype_data.py from backend/app/data/archetypes/.",
        "// Do not edit — change the JSON and rerun the script.",
        "package com.tracks.core.strengthplan",
        "",
    ]
    for kind, name in (("strength", "STRENGTH_ARCHETYPE_FILES"), ("flows", "FLOW_ARCHETYPE_FILES")):
        lines.append(f"internal val {name}: List<Pair<String, String>> = listOf(")
        for fname, text in _files(kind):
            lines.append(f"    {_kotlin_string(fname)} to {_kotlin_string(text)},")
        lines.append(")")
        lines.append("")
    return OUT, "\n".join(lines)


def main() -> None:
    out, text = render()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text)
    print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
