# SPDX-FileCopyrightText: 2026 Hawk Fugagli
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Baseline the goal-planning corpus: the recommended event date
(calculators/event_date.py) and which edits make a plan stale
(calculators/plan/staleness.py).

com.tracks.core.plan.EventDate and PlanStaleness replay every case: the web
shows the server's date and the phone computes its own offline, so the two
must land on the same day with the same reasons. Nothing here is personal —
fitness is a grid of made-up numbers.

    docker run --rm --env-file .env -v "$PWD/backend:/app" -v "$PWD/spec:/spec" \\
        tracks-backend python /spec/make_goal_planning_fixtures.py
"""
from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, "/app")

from app.calculators import event_date as ed  # noqa: E402
from app.calculators.plan import staleness as st  # noqa: E402

OUT = Path("/spec/fixtures/goal_planning.json")

# Every sport the goal form offers, at the distances its presets carry (and
# none), so every branch of the speed table and the general curve is walked.
EVENTS = [
    ("running", None), ("running", 5000.0), ("running", 10000.0), ("running", 16093.0),
    ("running", 21097.0), ("running", 42195.0), ("running", 100000.0), ("running", 160934.0),
    ("cycling", 20000.0), ("cycling", 100000.0), ("cycling", 321869.0),
    ("mountain biking", 80467.0), ("swimming", 750.0), ("swimming", 10000.0),
    ("triathlon", 12900.0), ("triathlon", 51500.0), ("triathlon", 113000.0), ("triathlon", 226000.0),
    ("hiking", None), ("skiing", None), ("rowing", 2000.0), ("other", None),
    ("strength_training", None),
]

# (ctl, sport share of the last six weeks, total TSS): none at all, a
# beginner, a fit specialist, a fit athlete from another sport, a very fit one.
FITNESS = [(0.0, 0.0, 0.0), (12.4, 1.0, 400.0), (48.5, 0.9, 1800.0), (55.0, 0.0, 2000.0), (95.2, 1.0, 3900.0)]

# A Monday, a Saturday and a Sunday, so the move to the next Sunday is exercised.
TODAYS = [date(2026, 9, 28), date(2026, 10, 3), date(2026, 10, 4)]


def main() -> None:
    cases = []
    for (sport, dist) in EVENTS:
        for (ctl, share, total) in FITNESS:
            for today in TODAYS:
                sport_tss = round(total * share, 3)
                cases.append({
                    "sport": sport, "distance_m": dist, "today": today.isoformat(),
                    "ctl": ctl, "sport_tss": sport_tss, "total_tss": total,
                    "expect": ed.recommend_event_date(sport, dist, today, ctl, sport_tss, total),
                })

    event_sports = ["running", "cycling", "mountain biking", "triathlon", "swimming", "other", "skiing", "rowing"]
    activity_sports = ["running", "trail_running", "cycling", "mountain_biking", "swimming",
                       "open_water_swimming", "hiking", "strength_training", "rowing", None]
    counts = [{"event": e, "activity": a, "expect": ed.counts_toward(e, a)}
              for e in event_sports for a in activity_sports]

    edits = [
        {}, {"notes": "x"}, {"event_name": "Boston"}, {"notes": "x", "event_name": "y"},
        {"is_active": False}, {"is_active": True}, {"days_per_week": 4}, {"plan_intensity": 1.1},
        {"strength_tier": 2}, {"include_strength": True}, {"strength_days_per_week": 2},
        {"event_date": "2027-01-01"}, {"event_sport": "cycling"}, {"event_distance_meters": 5000.0},
        {"ctl_ramp_per_week": 1.5}, {"target_weekly_km": 40.0}, {"fitness_sports": ["running"]},
        {"notes": "x", "days_per_week": 3},
    ]
    goal_edits = [{"changed": c, "expect": st.goal_edit_stales_plan(c)} for c in edits]

    fx = {
        "_comment": "Generated by spec/make_goal_planning_fixtures.py. Do not edit.",
        "event_date": cases,
        "counts_toward": counts,
        "non_plan_goal_fields": sorted(st.NON_PLAN_GOAL_FIELDS),
        "plan_settings": sorted(st.PLAN_SETTINGS),
        "goal_edits": goal_edits,
    }
    OUT.write_text(json.dumps(fx, indent=1) + "\n")
    print(f"wrote {len(cases)} event-date cases to {OUT}")


if __name__ == "__main__":
    main()
