// SPDX-FileCopyrightText: 2026 Hawk Fugagli
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED FILE — DO NOT EDIT.
//
// Source: spec/sync.yaml
// Regenerate: python3 spec/codegen.py
//
// Edits here are silently discarded on the next codegen run. The tables are
// shared across the Python backend, the JS frontend, and the Kotlin mobile
// core precisely so they cannot drift apart — change the spec, not this.

package com.tracks.core.replica

internal const val SYNC_SPEC_VERSION: Int = 1

internal const val UID_NAMESPACE: String = "6f1c6b1e-2b0e-4d6a-9c1e-7a3f0d5e8b42"

internal const val HLC_MAX_SKEW_MS: Long = 86400000L

internal const val PULL_DEFAULT_LIMIT: Int = 500

internal const val PULL_MAX_LIMIT: Int = 2000

internal val ENTITY_SPECS: List<EntitySpec> = listOf(
    EntitySpec(
        name = "settings",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "units", "theme_mode", "accent_color", "timezone", "weight_kg", "height_cm", "sex", "birth_year", "max_hr_mode", "max_hr_manual", "threshold_hr_mode", "threshold_hr_manual", "ftp_mode", "ftp_manual", "css_mode", "css_manual", "hidden_sports", "chart_resolution", "pace_coaching", "equipment_available", "strength_experience", "activity_frequency", "experience_suggestion_dismissed", "tour_seen", "tour_enabled", "weather_enabled", "weather_location", "map_enabled", "wildfire_enabled", "agps_enabled", "agps_source", "agps_custom_url", "agps_max_age_hours", "setup_complete"),
        refs = mapOf(),
        uidKey = "settings",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "device",
        kind = EntityKind.SOURCE,
        fields = listOf("serial_number", "manufacturer", "manufacturer_id", "product_name", "product_id", "software_version", "label", "is_primary"),
        refs = mapOf(),
        uidKey = "device:{serial_number}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "fit_file",
        kind = EntityKind.LOG,
        fields = listOf("sha256", "size_bytes", "file_kind", "device_serial", "started_at", "filename"),
        refs = mapOf(),
        uidKey = "fit:{sha256}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "activity",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "notes", "sport", "sub_sport", "hidden"),
        refs = mapOf(),
        uidKey = "activity:{device_serial}:{start_epoch_s}",
        uidKeyFallback = "activity:sha256:{sha256}",
        childOf = null,
    ),
    EntitySpec(
        name = "trip",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "notes", "activity_uids", "track_uids"),
        refs = mapOf("activity_uids" to "activity", "track_uids" to "track"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "daily_entry",
        kind = EntityKind.SOURCE,
        fields = listOf("date", "weight_kg", "hydration_ml", "calories_in"),
        refs = mapOf(),
        uidKey = "daily:{date}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "goal",
        kind = EntityKind.SOURCE,
        fields = listOf("goal_type", "is_active", "event_name", "event_sport", "event_date", "event_distance_meters", "ctl_ramp_per_week", "fitness_sports", "target_weekly_km", "volume_sport", "days_per_week", "plan_intensity", "mtb_discipline", "cycling_discipline", "schedule_tests", "include_strength", "strength_tier", "strength_days_per_week", "strength_session_minutes", "notes"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "race_plan",
        kind = EntityKind.SOURCE,
        fields = listOf("goal_uid", "split_type", "split_spread", "course_type", "pace_hr_mode", "pin_lat", "pin_lon", "use_gpx_distance", "course_segments", "course_path", "technicality_factor", "technicality_label", "target_hr_ceiling", "fueling_plan", "lap_paces", "triathlon_splits_m", "watch_filename", "watch_uploaded_at", "fuel_carbs_per_hour", "fuel_fluid_ml_per_hour", "fuel_sodium_mg_per_hour", "fuel_interval_min", "fuel_product_uids"),
        refs = mapOf("goal_uid" to "goal"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "plan",
        kind = EntityKind.SOURCE,
        fields = listOf("goal_uid", "sport", "vdot", "generation"),
        refs = mapOf("goal_uid" to "goal"),
        uidKey = "plan:{goal_uid}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "planned_workout",
        kind = EntityKind.SOURCE,
        fields = listOf("plan_uid", "generation", "scheduled_date", "sport", "workout_type", "title", "description", "duration_minutes", "distance_meters", "steps", "is_complete", "completed_activity_uid", "completion_pct", "custom_workout_uid", "custom_workout_name", "recap_completed_at", "origin", "watch_filename", "watch_uploaded_at", "watch_deleted_at", "fit_time_created", "fuel_carbs_per_hour", "moved_by_user"),
        refs = mapOf("plan_uid" to "plan", "completed_activity_uid" to "activity", "custom_workout_uid" to "workout"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = ChildOf(field = "plan_uid", entity = "plan"),
    ),
    EntitySpec(
        name = "workout",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "description", "tags", "include_in_plan", "sync_to_watch"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "workout_exercise",
        kind = EntityKind.SOURCE,
        fields = listOf("workout_uid", "exercise_name", "exercise_source", "target_reps", "target_sets", "rir_target", "rest_seconds", "weight_method", "weight_value", "order", "notes", "item_kind", "group_uid", "group_kind", "group_rounds", "group_rest_seconds"),
        refs = mapOf("workout_uid" to "workout"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = ChildOf(field = "workout_uid", entity = "workout"),
    ),
    EntitySpec(
        name = "workout_session",
        kind = EntityKind.LOG,
        fields = listOf("workout_uid", "planned_workout_uid", "session_data", "completed_at", "total_volume_kg", "session_rpe", "notes"),
        refs = mapOf("workout_uid" to "workout", "planned_workout_uid" to "planned_workout"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "exercise_preference",
        kind = EntityKind.SOURCE,
        fields = listOf("exercise_name", "preference"),
        refs = mapOf(),
        uidKey = "exercise_pref:{exercise_name}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "custom_exercise",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "primary_muscles", "secondary_muscles", "equipment", "movement_pattern", "is_compound", "difficulty", "description", "instructions", "cues", "viewer_slug", "default_sets", "default_reps", "garmin_category", "garmin_subtype", "has_animation"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "one_rep_max",
        kind = EntityKind.SOURCE,
        fields = listOf("exercise_name", "override_1rm_kg"),
        refs = mapOf(),
        uidKey = "orm:{exercise_name}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "animation_confirmation",
        kind = EntityKind.SOURCE,
        fields = listOf("product_id", "garmin_category", "garmin_subtype", "animates"),
        refs = mapOf(),
        uidKey = "anim:{product_id}:{garmin_category}:{garmin_subtype}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "flow",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "description", "include_in_plan", "sync_to_watch", "tags"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "flow_stretch",
        kind = EntityKind.SOURCE,
        fields = listOf("flow_uid", "exercise_name", "order", "sets", "duration_seconds", "rest_seconds", "coaching_note", "item_kind", "group_uid", "group_kind", "group_rounds", "group_rest_seconds"),
        refs = mapOf("flow_uid" to "flow"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = ChildOf(field = "flow_uid", entity = "flow"),
    ),
    EntitySpec(
        name = "stretch_preference",
        kind = EntityKind.SOURCE,
        fields = listOf("exercise_name", "preference"),
        refs = mapOf(),
        uidKey = "stretch_pref:{exercise_name}",
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "custom_stretch",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "primary_muscles", "secondary_muscles", "equipment", "movement_pattern", "is_compound", "difficulty", "duration_per_side_sec", "each_side", "sets", "description", "instructions", "cautions", "cues", "breath_cue", "position", "viewer_slug", "garmin_category", "garmin_subtype", "has_animation"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "medication",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "dose", "dose_unit", "form", "notes", "is_active"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "medication_schedule",
        kind = EntityKind.SOURCE,
        fields = listOf("medication_uid", "time_of_day", "days_of_week", "start_date", "end_date", "notify", "is_as_needed"),
        refs = mapOf("medication_uid" to "medication"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = ChildOf(field = "medication_uid", entity = "medication"),
    ),
    EntitySpec(
        name = "medication_log",
        kind = EntityKind.LOG,
        fields = listOf("medication_uid", "schedule_uid", "status", "scheduled_for", "logged_at", "notes"),
        refs = mapOf("medication_uid" to "medication", "schedule_uid" to "medication_schedule"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "injury",
        kind = EntityKind.SOURCE,
        fields = listOf("body_part", "injury_type", "severity", "start_date", "end_date", "notes"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "meal",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "calories", "protein_g", "carbs_g", "fat_g", "notes"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "meal_log",
        kind = EntityKind.LOG,
        fields = listOf("meal_uid", "name", "calories", "protein_g", "carbs_g", "fat_g", "logged_at", "notes"),
        refs = mapOf("meal_uid" to "meal"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "fuel_product",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "kind", "carbs_g", "sodium_mg", "caffeine_mg", "fluid_ml", "serving", "notes"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "gut_training_log",
        kind = EntityKind.LOG,
        fields = listOf("planned_workout_uid", "activity_uid", "date", "duration_min", "carbs_g", "comfort", "notes"),
        refs = mapOf("planned_workout_uid" to "planned_workout", "activity_uid" to "activity"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "track_folder",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "color", "load_to_device"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "track",
        kind = EntityKind.SOURCE,
        fields = listOf("folder_uid", "name", "color", "source", "sport", "activity_uid", "geometry", "distance_m", "ascent_m", "descent_m", "bounds", "profile", "turn_by_turn", "course_points", "is_external", "device_size", "hidden", "load_to_device", "watch_filename", "watch_uploaded_at", "watch_deleted_at", "purge_after_delete", "notes"),
        refs = mapOf("folder_uid" to "track_folder", "activity_uid" to "activity"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "waypoint",
        kind = EntityKind.SOURCE,
        fields = listOf("name", "lat", "lng", "ele_m", "color", "icon", "notes", "load_to_device", "watch_filename", "watch_uploaded_at", "watch_deleted_at"),
        refs = mapOf(),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
    EntitySpec(
        name = "coaching_note",
        kind = EntityKind.READONLY,
        fields = listOf("date", "goal_uid", "ai_response", "generated_at"),
        refs = mapOf("goal_uid" to "goal"),
        uidKey = null,
        uidKeyFallback = null,
        childOf = null,
    ),
)
