// SPDX-FileCopyrightText: 2026 Hawk Fugagli
// SPDX-License-Identifier: AGPL-3.0-or-later
package nodomain.freeyourgadget.gadgetbridge;

/**
 * Shim for the BuildConfig the vendored code expects.
 *
 * Gadgetbridge's is generated by its own build. The vendored protocol code
 * reads it to gate debug logging and to report a version to the watch during
 * handshake, so it needs to exist with those fields — it does not need to be
 * generated.
 */
public final class BuildConfig {
    private BuildConfig() {}

    public static final boolean DEBUG = false;

    /**
     * Reported to the watch during handshake as the companion-app version.
     * Tracks' own version, not Gadgetbridge's: this identifies the app that is
     * actually talking to the device.
     */
    public static final String VERSION_NAME = "tracks-0.1.0";
    public static final int VERSION_CODE = 1;
    public static final String APPLICATION_ID = "com.tracks.app";
}
