// SPDX-FileCopyrightText: 2026 Hawk Fugagli
// SPDX-License-Identifier: AGPL-3.0-or-later
package com.tracks.core.crypto

import java.security.SecureRandom
import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * The test that makes the sealed-box implementation trustworthy.
 *
 * Reading a hand-composed cryptographic construction and agreeing that it looks
 * right is worth very little; a single swapped step produces code that is
 * self-consistent and completely wrong. What is worth something is decrypting a
 * ciphertext produced by *the other implementation* — the server's own PyNaCl,
 * which is what will actually have to open these files.
 *
 * The vector below was generated by running PyNaCl inside the Tracks backend
 * container:
 *
 * ```python
 * from nacl.public import PrivateKey, SealedBox
 * sk = PrivateKey.generate()
 * sealed = SealedBox(sk.public_key).encrypt(message)
 * ```
 *
 * If BLAKE2b, X25519, HSalsa20, XSalsa20 or Poly1305 were wired up wrongly —
 * or merely in the wrong order — [opens_a_ciphertext_produced_by_pynacl] could
 * not pass. Everything else here is a property test on top of that anchor.
 */
@OptIn(ExperimentalEncodingApi::class)
class SealedBoxVectorTest {

    private val crypto = BouncyCastleIngestCrypto()

    private val recipientSecret = Base64.decode("jWpW9mwbOseP5Dg0dCBTa67tDKzd2LwMnaIorwFP8EM=")
    private val recipientPublic = Base64.decode("HJD1+3bJPkD64geqS+OeiJR7qklDqp+YssU/Cmm4RkE=")
    private val message = Base64.decode(
        "LkZJVCB0cmFja3Mgc2VhbGVkLWJveCBjcm9zcy1pbXBsZW1lbnRhdGlvbiB2ZWN0b3IAAQL+/w==",
    )
    private val pyNaClSealed = Base64.decode(
        "Iyz/zJPkV09etDi0P7IZbmd/ZafNAZLlCEYF52JS3VvnAyV6xohOly7p7yjNszMXk5FLPFPG6Ymg" +
            "TyW/BJv6vel9wtgnbCuy/K3zkc6NE8YEgm3SNro5qsumogPYHZpdtP+s74fNAw==",
    )

    @Test
    fun `opens a ciphertext produced by pynacl`() {
        assertContentEquals(message, crypto.open(recipientSecret, pyNaClSealed))
    }

    @Test
    fun `our own sealed box round-trips`() {
        val sealed = crypto.seal(recipientPublic, message)
        assertContentEquals(message, crypto.open(recipientSecret, sealed))
    }

    @Test
    fun `overhead matches libsodium exactly`() {
        // 32 bytes of ephemeral public key plus a 16-byte Poly1305 tag. The
        // server sizes nothing on this, but a mismatch here means a structural
        // mistake that the round-trip alone might not surface.
        val sealed = crypto.seal(recipientPublic, message)
        assertEquals(message.size + 48, sealed.size)
        assertEquals(pyNaClSealed.size, sealed.size)
    }

    @Test
    fun `sealing the same bytes twice produces different ciphertext`() {
        // Every seal draws a fresh ephemeral key. This is why the server dedupes
        // on a hash of the plaintext rather than of what it receives — hashing
        // the ciphertext would make every retry look like a new activity.
        val first = crypto.seal(recipientPublic, message)
        val second = crypto.seal(recipientPublic, message)
        assertNotEquals(first.toList(), second.toList())
        assertContentEquals(message, crypto.open(recipientSecret, second))
    }

    @Test
    fun `a tampered ciphertext is rejected rather than returned`() {
        val sealed = crypto.seal(recipientPublic, message)
        // Flip a bit in the body, past the ephemeral key and the tag.
        sealed[sealed.size - 1] = (sealed[sealed.size - 1].toInt() xor 1).toByte()
        assertFailsWith<IllegalArgumentException> { crypto.open(recipientSecret, sealed) }
    }

    @Test
    fun `a tampered ephemeral key is rejected`() {
        val sealed = crypto.seal(recipientPublic, message)
        sealed[0] = (sealed[0].toInt() xor 1).toByte()
        assertFailsWith<IllegalArgumentException> { crypto.open(recipientSecret, sealed) }
    }

    @Test
    fun `an empty file still seals`() {
        // Not hypothetical: a watch can offer a zero-length file, and the
        // failure mode of refusing one is a sync that stops rather than skips.
        val sealed = crypto.seal(recipientPublic, ByteArray(0))
        assertEquals(48, sealed.size)
        assertContentEquals(ByteArray(0), crypto.open(recipientSecret, sealed))
    }

    @Test
    fun `a realistic activity file seals`() {
        // A few megabytes is an ordinary long ride, and the streaming cipher
        // path is different enough from the short one to be worth exercising.
        val big = ByteArray(3 * 1024 * 1024).also { SecureRandom().nextBytes(it) }
        val sealed = crypto.seal(recipientPublic, big)
        assertContentEquals(big, crypto.open(recipientSecret, sealed))
    }

    @Test
    fun `a wrong-sized public key is refused before anything is encrypted`() {
        assertFailsWith<IllegalArgumentException> {
            crypto.seal(ByteArray(31), message)
        }
    }

    @Test
    fun `sha256 matches the plaintext digest the server dedupes on`() {
        // Known vector: SHA-256 of the empty string.
        assertEquals(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            crypto.sha256Hex(ByteArray(0)),
        )
        // And lowercase hex, which is what the server compares against.
        val hash = crypto.sha256Hex(message)
        assertEquals(64, hash.length)
        assertTrue(hash.all { it in "0123456789abcdef" })
    }
}
