"""
SPDX-FileCopyrightText: 2026 Hawk Fugagli
SPDX-License-Identifier: AGPL-3.0-or-later

GENERATED FILE — DO NOT EDIT.

Source: spec/sync.yaml
Regenerate: python3 spec/codegen.py

Edits here are silently discarded on the next codegen run. The tables are
shared across the Python backend, the JS frontend, and the Kotlin mobile
core precisely so they cannot drift apart — change the spec, not this.
"""

VERSION = 1

HLC_MAX_SKEW_MS = 86400000

UID_NAMESPACE = "6f1c6b1e-2b0e-4d6a-9c1e-7a3f0d5e8b42"

DELETE_WINS = True

PULL_DEFAULT_LIMIT = 500

PULL_MAX_LIMIT = 2000

ENTITIES = {   'settings': {   'kind': 'source',
                    'table': 'user_settings',
                    'uid_key': 'settings',
                    'uid_key_fallback': None,
                    'fields': [   'name',
                                  'units',
                                  'theme_mode',
                                  'accent_color',
                                  'timezone',
                                  'weight_kg',
                                  'height_cm',
                                  'sex',
                                  'birth_year',
                                  'max_hr_mode',
                                  'max_hr_manual',
                                  'threshold_hr_mode',
                                  'threshold_hr_manual',
                                  'ftp_mode',
                                  'ftp_manual',
                                  'css_mode',
                                  'css_manual',
                                  'hidden_sports',
                                  'chart_resolution',
                                  'pace_coaching',
                                  'equipment_available',
                                  'strength_experience',
                                  'activity_frequency',
                                  'experience_suggestion_dismissed',
                                  'tour_seen',
                                  'tour_enabled',
                                  'weather_enabled',
                                  'weather_location',
                                  'map_enabled',
                                  'wildfire_enabled',
                                  'agps_enabled',
                                  'agps_source',
                                  'agps_custom_url',
                                  'agps_max_age_hours',
                                  'setup_complete'],
                    'refs': {},
                    'children_of': None},
    'device': {   'kind': 'source',
                  'table': 'devices',
                  'uid_key': 'device:{serial_number}',
                  'uid_key_fallback': None,
                  'fields': [   'serial_number',
                                'manufacturer',
                                'manufacturer_id',
                                'product_name',
                                'product_id',
                                'software_version',
                                'label',
                                'is_primary'],
                  'refs': {},
                  'children_of': None},
    'fit_file': {   'kind': 'log',
                    'table': 'pending_imports',
                    'uid_key': 'fit:{sha256}',
                    'uid_key_fallback': None,
                    'fields': [   'sha256',
                                  'size_bytes',
                                  'file_kind',
                                  'device_serial',
                                  'started_at',
                                  'filename'],
                    'refs': {},
                    'children_of': None},
    'activity': {   'kind': 'source',
                    'table': 'activities',
                    'uid_key': 'activity:{device_serial}:{start_epoch_s}',
                    'uid_key_fallback': 'activity:sha256:{sha256}',
                    'fields': ['name', 'notes', 'sport', 'sub_sport', 'hidden'],
                    'refs': {},
                    'children_of': None},
    'trip': {   'kind': 'source',
                'table': 'activities',
                'uid_key': None,
                'uid_key_fallback': None,
                'fields': ['name', 'notes', 'activity_uids', 'track_uids'],
                'refs': {'activity_uids': 'activity', 'track_uids': 'track'},
                'children_of': None},
    'daily_entry': {   'kind': 'source',
                       'table': 'daily_metrics',
                       'uid_key': 'daily:{date}',
                       'uid_key_fallback': None,
                       'fields': ['date', 'weight_kg', 'hydration_ml', 'calories_in'],
                       'refs': {},
                       'children_of': None},
    'goal': {   'kind': 'source',
                'table': 'training_goals',
                'uid_key': None,
                'uid_key_fallback': None,
                'fields': [   'goal_type',
                              'is_active',
                              'event_name',
                              'event_sport',
                              'event_date',
                              'event_distance_meters',
                              'ctl_ramp_per_week',
                              'fitness_sports',
                              'target_weekly_km',
                              'volume_sport',
                              'days_per_week',
                              'plan_intensity',
                              'mtb_discipline',
                              'cycling_discipline',
                              'schedule_tests',
                              'include_strength',
                              'strength_tier',
                              'strength_days_per_week',
                              'strength_session_minutes',
                              'notes'],
                'refs': {},
                'children_of': None},
    'race_plan': {   'kind': 'source',
                     'table': 'race_plans',
                     'uid_key': None,
                     'uid_key_fallback': None,
                     'fields': [   'goal_uid',
                                   'split_type',
                                   'split_spread',
                                   'course_type',
                                   'pace_hr_mode',
                                   'pin_lat',
                                   'pin_lon',
                                   'use_gpx_distance',
                                   'course_segments',
                                   'course_path',
                                   'technicality_factor',
                                   'technicality_label',
                                   'target_hr_ceiling',
                                   'fueling_plan',
                                   'lap_paces',
                                   'triathlon_splits_m',
                                   'watch_filename',
                                   'watch_uploaded_at',
                                   'fuel_carbs_per_hour',
                                   'fuel_fluid_ml_per_hour',
                                   'fuel_sodium_mg_per_hour',
                                   'fuel_interval_min',
                                   'fuel_product_uids'],
                     'refs': {'goal_uid': 'goal'},
                     'children_of': None},
    'plan': {   'kind': 'source',
                'table': 'training_plans',
                'uid_key': 'plan:{goal_uid}',
                'uid_key_fallback': None,
                'fields': ['goal_uid', 'sport', 'vdot', 'generation'],
                'refs': {'goal_uid': 'goal'},
                'children_of': None},
    'planned_workout': {   'kind': 'source',
                           'table': 'planned_workouts',
                           'uid_key': None,
                           'uid_key_fallback': None,
                           'fields': [   'plan_uid',
                                         'generation',
                                         'scheduled_date',
                                         'sport',
                                         'workout_type',
                                         'title',
                                         'description',
                                         'duration_minutes',
                                         'distance_meters',
                                         'steps',
                                         'is_complete',
                                         'completed_activity_uid',
                                         'completion_pct',
                                         'custom_workout_uid',
                                         'custom_workout_name',
                                         'recap_completed_at',
                                         'origin',
                                         'watch_filename',
                                         'watch_uploaded_at',
                                         'watch_deleted_at',
                                         'fit_time_created',
                                         'fuel_carbs_per_hour',
                                         'moved_by_user'],
                           'refs': {   'plan_uid': 'plan',
                                       'completed_activity_uid': 'activity',
                                       'custom_workout_uid': 'workout'},
                           'children_of': {'field': 'plan_uid', 'entity': 'plan'}},
    'workout': {   'kind': 'source',
                   'table': 'user_workouts',
                   'uid_key': None,
                   'uid_key_fallback': None,
                   'fields': [   'name',
                                 'description',
                                 'tags',
                                 'include_in_plan',
                                 'sync_to_watch'],
                   'refs': {},
                   'children_of': None},
    'workout_exercise': {   'kind': 'source',
                            'table': 'user_workout_exercises',
                            'uid_key': None,
                            'uid_key_fallback': None,
                            'fields': [   'workout_uid',
                                          'exercise_name',
                                          'exercise_source',
                                          'target_reps',
                                          'target_sets',
                                          'rir_target',
                                          'rest_seconds',
                                          'weight_method',
                                          'weight_value',
                                          'order',
                                          'notes',
                                          'item_kind',
                                          'group_uid',
                                          'group_kind',
                                          'group_rounds',
                                          'group_rest_seconds'],
                            'refs': {'workout_uid': 'workout'},
                            'children_of': {   'field': 'workout_uid',
                                               'entity': 'workout'}},
    'workout_session': {   'kind': 'log',
                           'table': 'user_workout_sessions',
                           'uid_key': None,
                           'uid_key_fallback': None,
                           'fields': [   'workout_uid',
                                         'planned_workout_uid',
                                         'session_data',
                                         'completed_at',
                                         'total_volume_kg',
                                         'session_rpe',
                                         'notes'],
                           'refs': {   'workout_uid': 'workout',
                                       'planned_workout_uid': 'planned_workout'},
                           'children_of': None},
    'exercise_preference': {   'kind': 'source',
                               'table': 'user_exercise_preferences',
                               'uid_key': 'exercise_pref:{exercise_name}',
                               'uid_key_fallback': None,
                               'fields': ['exercise_name', 'preference'],
                               'refs': {},
                               'children_of': None},
    'custom_exercise': {   'kind': 'source',
                           'table': 'user_custom_exercises',
                           'uid_key': None,
                           'uid_key_fallback': None,
                           'fields': [   'name',
                                         'primary_muscles',
                                         'secondary_muscles',
                                         'equipment',
                                         'movement_pattern',
                                         'is_compound',
                                         'difficulty',
                                         'description',
                                         'instructions',
                                         'cues',
                                         'viewer_slug',
                                         'default_sets',
                                         'default_reps',
                                         'garmin_category',
                                         'garmin_subtype',
                                         'has_animation'],
                           'refs': {},
                           'children_of': None},
    'one_rep_max': {   'kind': 'source',
                       'table': 'user_exercise_strength',
                       'uid_key': 'orm:{exercise_name}',
                       'uid_key_fallback': None,
                       'fields': ['exercise_name', 'override_1rm_kg'],
                       'refs': {},
                       'children_of': None},
    'animation_confirmation': {   'kind': 'source',
                                  'table': 'animation_confirmations',
                                  'uid_key': 'anim:{product_id}:{garmin_category}:{garmin_subtype}',
                                  'uid_key_fallback': None,
                                  'fields': [   'product_id',
                                                'garmin_category',
                                                'garmin_subtype',
                                                'animates'],
                                  'refs': {},
                                  'children_of': None},
    'flow': {   'kind': 'source',
                'table': 'user_flexibility_flows',
                'uid_key': None,
                'uid_key_fallback': None,
                'fields': [   'name',
                              'description',
                              'include_in_plan',
                              'sync_to_watch',
                              'tags'],
                'refs': {},
                'children_of': None},
    'flow_stretch': {   'kind': 'source',
                        'table': 'flow_stretches',
                        'uid_key': None,
                        'uid_key_fallback': None,
                        'fields': [   'flow_uid',
                                      'exercise_name',
                                      'order',
                                      'sets',
                                      'duration_seconds',
                                      'rest_seconds',
                                      'coaching_note',
                                      'item_kind',
                                      'group_uid',
                                      'group_kind',
                                      'group_rounds',
                                      'group_rest_seconds'],
                        'refs': {'flow_uid': 'flow'},
                        'children_of': {'field': 'flow_uid', 'entity': 'flow'}},
    'stretch_preference': {   'kind': 'source',
                              'table': 'user_flexibility_preferences',
                              'uid_key': 'stretch_pref:{exercise_name}',
                              'uid_key_fallback': None,
                              'fields': ['exercise_name', 'preference'],
                              'refs': {},
                              'children_of': None},
    'custom_stretch': {   'kind': 'source',
                          'table': 'user_custom_stretches',
                          'uid_key': None,
                          'uid_key_fallback': None,
                          'fields': [   'name',
                                        'primary_muscles',
                                        'secondary_muscles',
                                        'equipment',
                                        'movement_pattern',
                                        'is_compound',
                                        'difficulty',
                                        'duration_per_side_sec',
                                        'each_side',
                                        'sets',
                                        'description',
                                        'instructions',
                                        'cautions',
                                        'cues',
                                        'breath_cue',
                                        'position',
                                        'viewer_slug',
                                        'garmin_category',
                                        'garmin_subtype',
                                        'has_animation'],
                          'refs': {},
                          'children_of': None},
    'medication': {   'kind': 'source',
                      'table': 'medications',
                      'uid_key': None,
                      'uid_key_fallback': None,
                      'fields': [   'name',
                                    'dose',
                                    'dose_unit',
                                    'form',
                                    'notes',
                                    'is_active'],
                      'refs': {},
                      'children_of': None},
    'medication_schedule': {   'kind': 'source',
                               'table': 'medication_schedules',
                               'uid_key': None,
                               'uid_key_fallback': None,
                               'fields': [   'medication_uid',
                                             'time_of_day',
                                             'days_of_week',
                                             'start_date',
                                             'end_date',
                                             'notify',
                                             'is_as_needed'],
                               'refs': {'medication_uid': 'medication'},
                               'children_of': {   'field': 'medication_uid',
                                                  'entity': 'medication'}},
    'medication_log': {   'kind': 'log',
                          'table': 'medication_log',
                          'uid_key': None,
                          'uid_key_fallback': None,
                          'fields': [   'medication_uid',
                                        'schedule_uid',
                                        'status',
                                        'scheduled_for',
                                        'logged_at',
                                        'notes'],
                          'refs': {   'medication_uid': 'medication',
                                      'schedule_uid': 'medication_schedule'},
                          'children_of': None},
    'injury': {   'kind': 'source',
                  'table': 'injuries',
                  'uid_key': None,
                  'uid_key_fallback': None,
                  'fields': [   'body_part',
                                'injury_type',
                                'severity',
                                'start_date',
                                'end_date',
                                'notes'],
                  'refs': {},
                  'children_of': None},
    'meal': {   'kind': 'source',
                'table': 'meals',
                'uid_key': None,
                'uid_key_fallback': None,
                'fields': [   'name',
                              'calories',
                              'protein_g',
                              'carbs_g',
                              'fat_g',
                              'notes'],
                'refs': {},
                'children_of': None},
    'meal_log': {   'kind': 'log',
                    'table': 'meal_log',
                    'uid_key': None,
                    'uid_key_fallback': None,
                    'fields': [   'meal_uid',
                                  'name',
                                  'calories',
                                  'protein_g',
                                  'carbs_g',
                                  'fat_g',
                                  'logged_at',
                                  'notes'],
                    'refs': {'meal_uid': 'meal'},
                    'children_of': None},
    'fuel_product': {   'kind': 'source',
                        'table': 'fuel_products',
                        'uid_key': None,
                        'uid_key_fallback': None,
                        'fields': [   'name',
                                      'kind',
                                      'carbs_g',
                                      'sodium_mg',
                                      'caffeine_mg',
                                      'fluid_ml',
                                      'serving',
                                      'notes'],
                        'refs': {},
                        'children_of': None},
    'gut_training_log': {   'kind': 'log',
                            'table': 'gut_training_logs',
                            'uid_key': None,
                            'uid_key_fallback': None,
                            'fields': [   'planned_workout_uid',
                                          'activity_uid',
                                          'date',
                                          'duration_min',
                                          'carbs_g',
                                          'comfort',
                                          'notes'],
                            'refs': {   'planned_workout_uid': 'planned_workout',
                                        'activity_uid': 'activity'},
                            'children_of': None},
    'track_folder': {   'kind': 'source',
                        'table': 'custom_track_folders',
                        'uid_key': None,
                        'uid_key_fallback': None,
                        'fields': ['name', 'color', 'load_to_device'],
                        'refs': {},
                        'children_of': None},
    'track': {   'kind': 'source',
                 'table': 'custom_tracks',
                 'uid_key': None,
                 'uid_key_fallback': None,
                 'fields': [   'folder_uid',
                               'name',
                               'color',
                               'source',
                               'sport',
                               'activity_uid',
                               'geometry',
                               'distance_m',
                               'ascent_m',
                               'descent_m',
                               'bounds',
                               'profile',
                               'turn_by_turn',
                               'course_points',
                               'is_external',
                               'device_size',
                               'hidden',
                               'load_to_device',
                               'watch_filename',
                               'watch_uploaded_at',
                               'watch_deleted_at',
                               'purge_after_delete',
                               'notes'],
                 'refs': {'folder_uid': 'track_folder', 'activity_uid': 'activity'},
                 'children_of': None},
    'waypoint': {   'kind': 'source',
                    'table': 'waypoints',
                    'uid_key': None,
                    'uid_key_fallback': None,
                    'fields': [   'name',
                                  'lat',
                                  'lng',
                                  'ele_m',
                                  'color',
                                  'icon',
                                  'notes',
                                  'load_to_device',
                                  'watch_filename',
                                  'watch_uploaded_at',
                                  'watch_deleted_at'],
                    'refs': {},
                    'children_of': None},
    'coaching_note': {   'kind': 'readonly',
                         'table': 'coaching_recommendations',
                         'uid_key': None,
                         'uid_key_fallback': None,
                         'fields': ['date', 'goal_uid', 'ai_response', 'generated_at'],
                         'refs': {'goal_uid': 'goal'},
                         'children_of': None}}
